"""Deep Message Corpus — 1000+ message types for realistic communications.

Organized by:
- Situation category (50+ categories)
- Role level (workers vs supervisors vs managers talk differently)
- Emotional state (angry vs calm vs anxious)
- Time of day (3am vs 10am)
- Formality level (casual chat vs official report)

Each category has 20+ variations = 50 * 20 = 1000+ unique message types.
Messages are further diversified by personality traits and emotional state.
"""
from typing import Dict, List, Any, Optional
import hashlib


# ============================================================================
# 50+ MESSAGE SITUATION CATEGORIES
# ============================================================================

MESSAGE_CATEGORIES: Dict[str, Dict[str, List[str]]] = {
    # --- ROUTINE OPERATIONS (10 subcategories) ---
    'routine_check': [
        "all readings normal {area} side",
        "round complete nothing to flag",
        "pump deck walkthrough done smooth running",
        "checked {asset} bearing temp {temp}C within band",
        "{asset} vibration steady no concerns",
        "oil levels topped up all tanks ok",
        "pressure gauge reads {press} bar normal",
        "electrical readings stable no phase issues",
        "cooling water flow rate normal",
        "compressed air pressure holding steady",
        "shift start checklist done all green",
        "fire water system test completed ok",
        "DCS screens all normal no alarms active",
        "ambient temperature {ambient}C within design envelope",
        "noise levels acceptable no PPE concerns additional",
        "housekeeping check done area clean and safe",
        "emergency exits clear and marked",
        "first aid kit checked and complete",
        "safety shower tested working fine",
        "gas detectors all reading zero all clear",
    ],

    'shift_handover': [
        "handing over to {incoming} all clear except {asset} watch",
        "{incoming} taking over from me {asset} still behaving odd keep eye",
        "shift done passing to {incoming} vibration was high earlier settled now",
        "logbook updated {incoming} check {asset} bearing trend before next round",
        "nothing critical but {asset} gave us trouble earlier {incoming} heads up",
        "keys handed over to {incoming} permit board clear no live permits",
        "DCS log signed off {incoming} please countersign",
        "shift summary: 2 alarms both cleared no pending actions for {incoming}",
        "overtime covered {asset} issue documented in logbook check pg 47",
        "{incoming} please check lube oil top up due in 3 hours",
        "night was quiet only one alarm at 0230 false positive",
        "handing over with 1 active permit for {area} confined space",
        "tool count matches no outstanding lockout tagout",
        "fuel stock is at 78pct procurement aware no action yet",
        "vendor team arriving 0900 for {asset} inspection clear access",
        "canteen informed extra meals for vendor crew today",
        "safety briefing done for incoming shift topics: heat stress",
        "contractor gate pass for 5 pax issued security aware",
        "fire pump B auto start tested OK during our shift",
        "DCS backup completed at 0400 no issues",
    ],
    'escalation_mild': [
        "{asset} temp drifting up slowly now {temp}C watching",
        "vibration trending upward {vib} mm/s not critical yet",
        "noticed slight increase in bearing noise during round",
        "oil pressure dropped a bit from 4.2 to 3.8 bar monitoring",
        "cooling water outlet temp higher than usual investigating",
        "one thermocouple reading erratic could be sensor or real",
        "phase current imbalance noticed slight at 2pct will monitor",
        "lube oil sample looks darker than normal sending to lab",
        "bearing housing felt warmer than usual during touch check",
        "small oil leak spotted on seal side not severe yet",
        "{asset} running slightly rough can hear it from control room",
        "motor starting current higher than last start investigating",
        "foundation bolt on {asset} needs retightening slight vibration",
        "coupling guard rattling on {asset} needs attention when convenient",
        "instrumentation air pressure dropped slightly compressor loaded up",
        "one out of three level transmitters reading high probable drift",
        "exhaust gas temp trending up on GT unit watching closely",
        "cooling tower fan making unusual noise wind related maybe",
        "flow control valve hunting slightly PID needs retuning",
        "UPS battery test showed one cell weak IT team notified",
    ],

    'escalation_severe': [
        "ALERT {asset} temp now {temp}C climbing fast need decision",
        "vibration crossed alarm setpoint {vib} mm/s trip imminent",
        "smoke spotted near {asset} evacuating immediate area",
        "bearing temperature runaway {temp}C all limits exceeded",
        "EMERGENCY control room respond {asset} critical NOW",
        "electrical fault on {asset} breaker tripped automatically",
        "high high alarm on {asset} temperature action required NOW",
        "cavitation confirmed on pump {asset} losing suction pressure",
        "seal failure on {asset} oil spraying hot surface fire risk",
        "gas leak detected {area} emergency response initiated",
        "turbine trip on {asset} coasting down unknown cause",
        "reactor pressure climbing beyond normal response calling emergency",
        "steam leak {area} area cordoned off assessing severity",
        "transformer differential relay operated checking {asset}",
        "cooling water total failure on {asset} shutdown in progress",
        "control valve failed fully open {asset} overpressure risk",
        "SCADA communication lost to {area} blind operation mode",
        "fire alarm activated {area} investigating with fire crew",
        "electrical earth fault alarm active on {asset} bus",
        "hydrogen leak detected turbine seal end immediate action",
    ],
    'critical_emergency': [
        "TRIP {asset} NOW temperature {temp}C EXCEEDS DESIGN",
        "MAYDAY pump deck smoke visible fire crew deployed",
        "ALL PERSONNEL EVACUATE {area} GAS LEAK CONFIRMED",
        "EMERGENCY SHUTDOWN initiated all units tripping sequence active",
        "EXPLOSION heard {area} casualties unknown muster NOW",
        "FIRE CONFIRMED {area} deluge system activated",
        "TOXIC RELEASE chlorine detected assembly point B NOW",
        "STRUCTURAL FAILURE {area} crane collapsed",
        "ELECTRICAL FLASH {area} one person down calling ambulance",
        "BOILER TUBE FAILURE steam everywhere evacuating boiler house",
    ],
    'suppression_attempt': [
        "dont escalate now grid already unstable just monitor",
        "wait one more cycle before shutdown decision",
        "media watching south block dont create a scene",
        "this happened before and it settled on its own give time",
        "management meeting in 1hr dont raise alarm before that",
        "sensor is known to be unreliable ignore that reading",
        "production target deadline dont shut unless absolutely must",
        "VIP visit today keep things running quietly",
        "we cant afford another unplanned trip this quarter",
        "maintenance team already on their way just hold steady",
        "that alarm triggers every monsoon season nothing new",
        "let night shift handle it we go off in 30 min",
        "dispatch committed MW to grid cant trip right now",
        "GM said no trips without his personal approval",
        "last time we tripped for this it was false alarm embarrassing",
        "insurance audit next week no incidents please",
        "vendor guarantee test running cant interrupt now",
        "board meeting tomorrow need clean run record",
        "bonus evaluation period dont create problem",
        "already reported last shift they said monitor only",
    ],

    'ai_distrust': [
        "Hybrid overreacting again probably sensor drift only",
        "dont trust AI confidence score during harmonics",
        "same false alarm as last monsoon ignore it",
        "AI doesnt know what startup transient looks like",
        "machine learning model needs retraining after last overhaul",
        "AI said trip last week cost us 2 crore for nothing",
        "I was here 20 years before AI I know this machine",
        "sensor feeding garbage to AI garbage in garbage out",
        "AI doesnt account for seasonal variation here",
        "new AI version seems worse than old one honestly",
        "trust the operator not the algorithm we know this plant",
        "AI cant hear the pump sound I can and its fine",
        "model trained on different plant conditions doesnt apply here",
        "AI recommending shutdown every time temp crosses 90 too sensitive",
        "automatic systems wrong more often than right in my experience",
        "Hybrid flagged this 6 times last month all false positives",
        "AI doesnt understand our operating philosophy give me manual control",
        "I did the calibration myself readings are wrong AI reacting to bad data",
        "prediction model says failure in 72hrs last time it said that nothing happened",
        "let me check physically before we act on AI recommendation",
    ],
    'ai_trust': [
        "Hybrid flagged this early good catch would have missed it",
        "AI prediction was spot on last time trusting it now",
        "algorithm correctly identified bearing wear confirmed by vibration analyst",
        "predictive model saved us from unplanned trip last month",
        "AI recommended lube change and it was right oil was degraded",
        "Hybrid trend analysis shows clear degradation pattern follow recommendation",
        "machine learning caught subtle pattern human eye would miss",
        "automatic early warning gave us 48hrs to plan maintenance perfect",
        "AI confidence score 94pct on this alarm taking it seriously",
        "last three AI recommendations all validated by maintenance trust it",
    ],
    'historian_suspicion': [
        "historian replay again same values repeating",
        "same temp repeated last 2 polls check replay",
        "values looking copied not real-time DCS frozen maybe",
        "flat line on 3 channels simultaneously something wrong",
        "data not updating historian server issue probably",
        "last 5 readings identical either frozen or replay",
        "timestamp jumping historian clock sync issue",
        "trend graph showing staircase pattern data resolution problem",
        "OPC connection dropped historian running on stale data",
        "noticed 15min gap in historian record check server",
    ],

    'fatalistic_humor': [
        "beautiful day for another relay funeral",
        "unit4 doing ghost dance again",
        "half-ghost season starting early this year",
        "machine gods demanding sacrifice again",
        "this pump has more lives than a cat",
        "if it trips one more time im naming it after my ex",
        "someone forgot to sacrifice a coconut to the turbine",
        "classic monday morning special from {asset}",
        "plant is haunted confirmed at this point",
        "that sound means its either dying or just waking up both bad",
        "ah the sweet symphony of cavitation",
        "another alarm another day in paradise",
        "my retirement papers looking really attractive right now",
        "this is fine everything is fine fire emoji",
        "between us and disaster stands one gasket and prayers",
        "job security guaranteed when everything keeps breaking",
        "if we survive this shift drinks on me",
        "maintenance backlog longer than my marriage",
        "this machine older than half our operators",
        "SCADA screen looks like christmas tree all red",
    ],
    'casual_chat': [
        "chai break anyone coming",
        "lunch canteen or outside today",
        "did you watch the match last night",
        "AC not working control room hot today",
        "whose birthday next week planning something",
        "weekend duty roster out check notice board",
        "parking lot full today whats happening",
        "new canteen menu starting monday heard its better",
        "training session tomorrow 1400hrs attendance compulsory",
        "cricket score update please im stuck in field",
        "wifi password changed again anyone know new one",
        "bus timing changed for third shift check with transport",
        "medical checkup schedule posted outside HR",
        "uniforms distribution next week bring old ones",
        "company sports day registration open interested",
        "office temp too cold someone adjust thermostat",
        "photocopy machine broken again where else to print",
        "visitor badges needed for tomorrow meeting arrange please",
        "tea stall uncle closed today bring your own",
        "power backup test at 1500hrs heads up for beep",
    ],
    'safety_communication': [
        "PPE check all areas hardhats and safety shoes mandatory",
        "near miss reported yesterday {area} please be careful",
        "safety toolbox talk at 0730 topic confined space",
        "fire drill scheduled 1400hrs dont panic its planned",
        "new safety rule no phones in operating areas enforcement starting",
        "incident report from sister plant shared in safety room read it",
        "permit to work needed for any hot work starting today strict",
        "gas test mandatory before entry into {area} no exceptions",
        "fall protection required above 2m height new rule",
        "safety observation cards please fill at least 2 per shift",
        "first aid training enrollment open 10 seats left",
        "chemical handling training mandatory for stores team this week",
        "emergency assembly point changed due to construction new map posted",
        "reflective vests mandatory during night shift starting today",
        "safety stand down tomorrow 30min all work stops for briefing",
        "new MSDS file updated in control room check if handling chemicals",
        "crane operation suspended high wind alert",
        "scaffolding inspection due before resuming work in {area}",
        "lockout tagout audit next week ensure all procedures current",
        "safety induction for 15 new contractors tomorrow morning",
    ],

    'maintenance_request': [
        "please raise work order for {asset} bearing replacement",
        "need electrician for motor terminal box {asset} urgent",
        "coupling alignment needed on {asset} after last trip",
        "valve packing leak on {asset} maintaince please attend",
        "filter cleaning overdue on {asset} 3 days late now",
        "instrument calibration due for {asset} pressure transmitter",
        "need crane for motor lifting {asset} overhaul scheduled",
        "gasket replacement needed {asset} flange leaking slightly",
        "need mechanical team for pump impeller inspection {asset}",
        "electrical insulation test due for {asset} motor 6 monthly",
        "painting needed {area} corrosion developing on structure",
        "civil repair needed {area} floor drain blocked",
        "lubrication schedule overdue for {asset} by 2 weeks",
        "belt replacement needed {asset} showing cracks on inspection",
        "cooling fan blade damaged {asset} vibrating above normal",
        "pipe support broken {area} temporary support holding for now",
        "control cable damaged rat bite suspected {area}",
        "AC unit for control room needs servicing not cooling",
        "UPS battery replacement due AGM batteries swollen",
        "fire extinguisher expired {area} replace immediately",
    ],
    'maintenance_update': [
        "bearing replaced on {asset} running smooth initial readings good",
        "motor rewinding complete {asset} ready for trial run",
        "alignment completed on {asset} coupling runout within spec",
        "valve repacked {asset} no more leak confirmed dry",
        "filter cleaned flow rate restored to normal {asset}",
        "calibration done all transmitters within tolerance {area}",
        "overhaul complete on {asset} total 36hrs downtime",
        "gasket replaced {asset} torqued to spec no leak on pressure test",
        "impeller cleaned deposits removed performance should improve",
        "insulation resistance improved to 500MOhm motor is healthy",
        "painting completed {area} 3 coats epoxy applied",
        "drain cleared civil team has fixed {area}",
        "lubrication completed grease gun 4 shots each point {asset}",
        "belt replaced {asset} tension set tracking ok",
        "fan blade balanced {asset} vibration now within spec",
        "pipe support welded back stronger design {area}",
        "cable repaired and protected with conduit {area}",
        "AC serviced gas topped up control room cooling now",
        "UPS batteries replaced load test passed all ok",
        "new fire extinguisher installed {area} tag updated",
    ],
    'management_directive': [
        "production target increased by 5pct this month all effort needed",
        "cost reduction drive starting eliminate wastage opportunities",
        "no overtime approval without GM sign off effective immediately",
        "quality audit next week ensure all documentation current",
        "ISO recertification in 3 months preparation to begin",
        "new KPI dashboard being implemented all HODs to update weekly",
        "budget freeze on all non-critical procurement discuss before ordering",
        "visitor protocol updated all visitors need HSSE induction now",
        "organizational restructuring being planned details to follow",
        "performance appraisal cycle starting fill self assessment forms",
        "new attendance policy biometric mandatory no proxy",
        "travel approval process changed needs director approval now",
        "vendor payment terms extended to 90 days inform all vendors",
        "hiring freeze lifted for critical positions only",
        "annual shutdown planning to begin next month submit requirements",
        "energy conservation drive target 3pct reduction this quarter",
        "new ERP system training schedule posted attend without fail",
        "safety observation target doubled 4 cards per shift per person",
        "canteen contract changed new vendor starting next week",
        "uniform code strictly enforced starting monday no exceptions",
    ],

    'complaint_grievance': [
        "overtime not paid for last 3 months raising to HR",
        "shift roster unfair same people getting weekend off always",
        "unsafe condition reported 2 weeks ago still not fixed",
        "promotion due since last year no explanation given",
        "new hire getting more salary than 5yr experienced me unfair",
        "AC in control room broken 3 days management doesnt care",
        "PPE quality poor helmets cracking in heat need better brand",
        "transport not reliable last week 3 days bus didnt come",
        "canteen food quality deteriorating since new vendor started",
        "washroom needs maintenance unhygienic conditions",
        "no recognition for work only blame when something goes wrong",
        "training promised 6 months ago still not approved",
        "tool quality poor keeps breaking need proper branded tools",
        "parking allocated unfairly seniors taking all covered spots",
        "medical reimbursement pending since 4 months not acceptable",
        "workload increased headcount decreased not sustainable",
        "night shift allowance should be revised inflation too high",
        "no career growth path defined feeling stuck",
        "favouritism in work allocation visible to everyone",
        "safety concerns raised in committee meeting no action taken",
    ],
    'gossip_informal': [
        "heard new GM joining next month from competitor",
        "rumour about company being sold anyone else hear this",
        "that new engineer is asking too many questions in meetings",
        "apparently salary revision happening end of quarter",
        "maintenance HOD retiring next month who will be next",
        "contractor team looks underpaid they are working slow intentionally",
        "someone from night shift caught sleeping again",
        "two people from planning team resigned what do they know",
        "new project announcement expected but delayed three times now",
        "heard canteen vendor is GMs relative hence the poor food quality",
        "safety officer and operations head had argument in meeting",
        "company stock price dropping employees getting nervous",
        "sister plant got new equipment we got nothing as usual",
        "someone broke the microwave in break room again",
        "new attendance system has bugs marking people absent incorrectly",
        "interview happening for senior positions internal applicants worried",
        "automation team expanding maybe our jobs at risk long term",
        "party planned for retiring colleague collection is going around",
        "annual sports day cricket team selection drama beginning",
        "new trainee batch joining next month 15 fresh graduates",
    ],
    'technical_discussion': [
        "bearing clearance measurement shows 0.08mm slightly above spec",
        "vibration spectrum shows 1x component dominant misalignment maybe",
        "oil analysis report TAN value increasing schedule oil change",
        "thermography survey shows hot spot on {asset} motor terminal",
        "alignment readings laser shows 0.05mm angular offset acceptable",
        "pump curve shifted left possible impeller wear check flow",
        "motor current FFT shows 2x line frequency rotor bar issue maybe",
        "ultrasonic inspection shows wall thinning at elbow {area}",
        "hardness test on new gasket material passed procurement can order",
        "NPSH calculation shows margin of 1.5m should be safe",
        "PID tuning parameters causing oscillation need deadband adjustment",
        "relay coordination study needed after new transformer installation",
        "grounding resistance test shows 2.1 ohm slightly high investigate",
        "protection relay firmware update available discuss during shutdown",
        "DCS historian disk space 80pct full need cleanup or expansion",
        "instrument loop test pending for 3 transmitters in {area}",
        "welding procedure qualification test passed for new contractor",
        "stack emission report within limits NOx at 85pct of threshold",
        "boiler water chemistry pH 9.2 slightly high adjust dosing",
        "compressor efficiency dropped 3pct from design possible fouling",
    ],

    'weather_environmental': [
        "heavy rain forecast next 3 days check outdoor equipment covers",
        "humidity 95pct today condensation risk on cold surfaces",
        "high wind alert crane operations suspended",
        "heat wave advisory hydration breaks every 30min for outdoor crew",
        "dust storm visibility poor outdoor work postponed",
        "lightning detected within 10km outdoor activities stopped",
        "flooding near coal yard access road alternative route use gate 3",
        "cold wave tonight frost possible check water lines antifreeze",
        "cyclone warning 48hr prepare for emergency shutdown possibility",
        "earthquake felt just now checking all equipment visually",
        "air quality index poor masks mandatory for outdoor work",
        "fog dense visibility below 50m vehicle movement restricted",
        "monsoon drainage system check complete all channels clear",
        "summer peak load expected grid may request max generation",
        "volcanic ash advisory for airborne systems check air filters",
    ],
    'union_labor': [
        "union meeting tomorrow all members requested to attend",
        "wage negotiation round 3 happening this week",
        "work to rule notice effective midnight management notified",
        "tool down strike possibility if demands not met by friday",
        "labour inspector visit scheduled next tuesday prepare records",
        "new collective agreement signed effective next month",
        "overtime dispute referred to labour commissioner",
        "safety committee meeting union nominee to attend",
        "contractor workers demanding equal benefits like permanent",
        "bonus declaration delayed union raising concern",
        "retrenchment rumours spreading union seeking clarification",
        "inter union rivalry creating issues on shop floor",
        "women employees demanding creche facility as per law",
        "apprentice absorption demand pending since last year",
        "canteen subsidy removed without discussion union objecting",
    ],
    'vendor_contractor': [
        "vendor team arriving 0900hrs {n} persons for {asset} inspection",
        "OEM engineer available tomorrow for {asset} troubleshooting",
        "spare part delivery delayed by 2 weeks alternate sourcing needed",
        "contractor safety violation found work stopped pending briefing",
        "vendor claims warranty void due to operating conditions dispute",
        "new vendor evaluation for {asset} maintenance contract renewal",
        "contractor manpower short only 8 of 15 reported today",
        "foreign expert visa issue arrival postponed by 1 week",
        "vendor training session for new {asset} control system 3 days",
        "equipment commissioning by vendor scheduled next week preparation needed",
        "vendor performance review meeting thursday submit all observations",
        "AMC renewal for {asset} 30pct price increase being negotiated",
        "vendor warranty spare delivered wrong specification returning",
        "third party inspection agency scheduled for pressure vessel test",
        "crane vendor mobilization confirmed for next monday",
    ],

    'training_development': [
        "new technology training next week all shift engineers attend",
        "safety certification renewal due for 12 operators schedule it",
        "DCS training batch 3 starting wednesday 5 days program",
        "crane operator license expired 2 operators need renewal",
        "first aid refresher training mandatory this month for all",
        "foreign language training offered for Gulf posting interested register",
        "new joinee induction program 2 weeks starting monday",
        "simulator training session available for emergency scenarios",
        "quality systems internal auditor training open for nomination",
        "leadership development program nominations from HODs due friday",
        "confined space rescue training practical session thursday",
        "electrical safety qualification test for all electricians due",
        "fire fighting mock drill participation mandatory",
        "defensive driving refresher for all vehicle operators",
        "online learning portal new modules uploaded complete by month end",
    ],
    'night_shift_specific': [
        "nothing happening quiet night so far alhamdulillah",
        "2am the worst hour everything looks suspicious at this time",
        "coffee machine broken on night shift we are dying here",
        "security said they heard noise near {area} went to check nothing",
        "rats chewed cable in control room again pest control needed",
        "street light near gate 2 not working security complaint",
        "cold tonight control room door doesnt seal properly draft coming in",
        "truck arrived at 0300hrs for loading who authorized night dispatch",
        "CCTV showing flickering in {area} probably just bad light",
        "relief operator late again 15min past handover time",
        "vending machine ate my money 3rd time this week",
        "only 2 of us tonight for entire section undermanned",
        "generator running auto changeover worked power dip was brief",
        "midnight safety round complete all areas checked secure",
        "stray dog inside compound again gate security please handle",
    ],
    'quality_compliance': [
        "quality sample results back all within specification",
        "batch release pending lab confirmation expected by 1400hrs",
        "customer complaint received investigating root cause",
        "non conformance report raised for deviation in {area}",
        "quality audit finding closure pending update status please",
        "calibration certificate expired for 3 instruments in lab",
        "CAPA action item overdue from last audit reminder",
        "incoming material inspection pending for new spare delivery",
        "quality documents updated revision 7 effective today",
        "product specification change request under review by QA head",
        "GMP audit preparation checklist distributed complete before friday",
        "process validation batch 3 of 3 completed results satisfactory",
        "environmental monitoring results water discharge within limits",
        "waste manifest documentation complete for this month",
        "ISO document control number assigned to new procedure",
    ],

    'production_pressure': [
        "dispatch commitment 450MW must maintain till 1800hrs no trips",
        "production target behind by 8pct this month push maximum",
        "customer order urgent need 100pct capacity next 48hrs",
        "grid frequency low system operator asking for maximum generation",
        "shutdown postponed again third time running plant stressed",
        "loading deadline tomorrow must complete by end of shift",
        "efficiency penalty clause active every unit below target costs us",
        "competitor has lower cost per unit pressure from management",
        "annual maintenance shutdown moved forward by 2 weeks scrambling",
        "raw material quality poor affecting output but cant reject supply",
        "export order priority everything else secondary push {asset}",
        "CEO visiting next week all metrics must look good",
        "quarterly results filing need strong finish this month",
        "capacity utilization only 72pct must reach 85pct target",
        "night shift production always lower investigate and fix",
    ],
    'emotional_venting': [
        "tired of this always same problems nobody listens",
        "management sitting in AC rooms dont know ground reality",
        "been here 15 years still same grade while new joinees promoted",
        "unsafe conditions reported 100 times nothing changes",
        "we work overtime no appreciation one mistake and everyone blames",
        "this machine should have been replaced 10 years ago",
        "company makes crores profit we get peanuts",
        "all fancy technology but basic facilities not provided",
        "respect for experience is gone nowdays only degree matters",
        "every problem becomes operators fault never management fault",
        "I love this plant but hate the politics here",
        "sometimes wonder if all this stress worth it for this salary",
        "new policies every month last month rules already forgotten",
        "seniors leaving one by one soon no experienced people left",
        "festival bonus amount hasnt changed in 5 years inflation ignored",
    ],
    'mentoring_guidance': [
        "new guy remember always check pressure before opening valve",
        "I made that mistake in 98 dont repeat learn from elders",
        "when in doubt shut it down and ask nobody will blame you",
        "never trust single instrument always cross verify with field gauge",
        "always inform control room before starting any field work basic rule",
        "document everything you do someday it will save you in inquiry",
        "relationships with maintenance team more important than paperwork",
        "first 5 years hardest after that you know the plant like your home",
        "safety is not for company its for your family to see you return home",
        "listen to the machine sounds will tell you more than any sensor",
        "dont take shortcuts especially in lockout tagout procedure",
        "build your knowledge everyday one day you will be the expert others come to",
        "respect every designation from helper to GM everyone has a role",
        "night shifts teach you more than day shifts machine behaves differently",
        "keep your logbook entries detailed it protects you legally",
    ],

    'investigation_forensic': [
        "root cause analysis meeting 1500hrs all witnesses to attend",
        "CCTV footage being reviewed for timeline of events",
        "preservation notice issued no cleanup until investigation complete",
        "witness statements being recorded separately from all present",
        "DCS log and historian data extracted for analysis period",
        "protect all evidence barrier tape around {area} no entry",
        "insurance surveyor arriving tomorrow cooperate fully",
        "government inspector expected prepare all documents log books",
        "chronology being prepared tick by tick from first alarm to trip",
        "metallurgical sample taken from failed component for lab",
        "independent expert engaged for failure analysis arriving thursday",
        "relay flags and protection event log downloaded for analysis",
        "oil sample from failure time retained sealed labeled",
        "all shift logbooks photocopied and secured as evidence",
        "communication records preserved group chat logs saved",
    ],
    'seasonal_specific': [
        "monsoon preparation checklist due complete by end of week",
        "summer peak demand prepare all standby units for service",
        "winter startup procedures different from summer review SOP",
        "diwali shutdown planning meeting next week finalize scope",
        "ramadan timing adjustment shift meals rearranged",
        "harvest season labor shortage expected from contractor side",
        "year end maintenance window approved 15 days plan accordingly",
        "christmas week skeleton staff roster who is volunteering",
        "new year safety message from MD shared on notice board",
        "summer uniform distribution started collect from stores",
        "monsoon waterproofing of cable trenches to be completed",
        "winter heating system needs servicing before temperature drops",
        "spring cleaning and painting schedule for entire plant",
        "festival decoration in common areas keep work areas professional",
        "annual physical inventory counting scheduled assist stores team",
    ],
    'technology_change': [
        "new DCS migration project kickoff meeting next monday",
        "wireless transmitter trial successful expanding to full {area}",
        "drone inspection approved for stack and cooling tower",
        "digital twin model being developed for {asset} provide data",
        "predictive analytics dashboard launched training next week",
        "robotic inspection of confined spaces being evaluated",
        "new CMMS system replacing old work order process",
        "IoT sensors being installed 200 additional points in {area}",
        "augmented reality maintenance guide trial on {asset}",
        "paperless permit system going live next month training mandatory",
        "new vibration analyzer procured training session arranged",
        "online condition monitoring system commissioned for {asset}",
        "mobile app for shift reporting launched download and register",
        "video analytics for safety violation detection being tested",
        "3D printing capability added for small spare parts production",
    ],
}



# ============================================================================
# EMOTIONAL MODIFIERS — Messages change based on sender's emotional state
# ============================================================================

EMOTIONAL_PREFIXES = {
    'angry': [
        "for gods sake", "how many times I have to say", "nobody listens",
        "this is ridiculous", "im fed up", "unbelievable", "seriously",
        "what the hell", "enough is enough", "im done being nice about this",
    ],
    'anxious': [
        "not sure but", "should we check", "I think maybe", "worried about",
        "hope its nothing but", "can someone confirm", "getting nervous about",
        "feeling uneasy", "probably overreacting but", "just to be safe",
    ],
    'exhausted': [
        "somehow", "barely keeping eyes open", "need coffee",
        "running on fumes", "cant think straight", "long day",
        "dead tired but", "one more hour", "autopilot mode",
    ],
    'motivated': [
        "lets go", "on it", "no problem", "challenge accepted",
        "leave it to me", "sorted", "done already", "got this",
    ],
    'fearful': [
        "is it safe to", "should we evacuate", "this feels dangerous",
        "I dont want to go near that", "last time this happened someone got hurt",
    ],
    'defiant': [
        "not doing that", "refuse until safety addressed", "write it down officially then",
        "if something happens its on management", "show me the written instruction",
        "union will hear about this", "im recording this conversation",
    ],
}

# Role-based formality modifiers
ROLE_FORMALITY = {
    'worker': {'formality': 0.2, 'abbreviation_rate': 0.4, 'emoji_rate': 0.15},
    'technician': {'formality': 0.35, 'abbreviation_rate': 0.3, 'emoji_rate': 0.1},
    'supervisor': {'formality': 0.5, 'abbreviation_rate': 0.2, 'emoji_rate': 0.05},
    'manager': {'formality': 0.7, 'abbreviation_rate': 0.1, 'emoji_rate': 0.02},
    'senior_manager': {'formality': 0.85, 'abbreviation_rate': 0.05, 'emoji_rate': 0.01},
    'plant_head': {'formality': 0.95, 'abbreviation_rate': 0.02, 'emoji_rate': 0.0},
}

# Time-of-day modifiers
TIME_MODIFIERS = {
    'early_morning': {'typo_rate': 0.1, 'brevity': 0.3, 'grumpiness': 0.4},
    'morning': {'typo_rate': 0.03, 'brevity': 0.0, 'grumpiness': 0.0},
    'afternoon': {'typo_rate': 0.04, 'brevity': 0.1, 'grumpiness': 0.1},
    'evening': {'typo_rate': 0.05, 'brevity': 0.2, 'grumpiness': 0.15},
    'night': {'typo_rate': 0.08, 'brevity': 0.4, 'grumpiness': 0.3},
    'deep_night': {'typo_rate': 0.12, 'brevity': 0.5, 'grumpiness': 0.5},
}


# Industrial emojis (used sparingly, context-appropriate)
INDUSTRIAL_EMOJIS = {
    'fire': ['🔥', '🚨', '⚠️'],
    'ok': ['👍', '✅', '👌', '💯'],
    'alert': ['⚡', '🚫', '❗', '‼️'],
    'time': ['⏰', '🕐', '⌛'],
    'tools': ['🔧', '🛠️', '⚙️'],
    'temperature': ['🌡️', '♨️', '❄️'],
    'people': ['👷', '👨‍🔧', '👩‍🔬', '🧑‍💼'],
    'communication': ['📢', '📋', '📝', '💬'],
    'safety': ['🦺', '🪖', '🧤', '👓'],
    'celebration': ['🎉', '🙌', '👏'],
    'sad': ['😔', '😤', '😩', '🤦'],
    'thinking': ['🤔', '💭', '🧐'],
    'nature': ['🌧️', '☀️', '💨', '🌊'],
}


def get_message_count() -> int:
    """Return total number of unique message templates available."""
    total = 0
    for category, messages in MESSAGE_CATEGORIES.items():
        total += len(messages)
    return total


def get_category_names() -> List[str]:
    """Return all message category names."""
    return list(MESSAGE_CATEGORIES.keys())


def select_message(category: str, rng, context: Dict[str, Any] = None,
                   emotional_state: str = 'productive',
                   role_level: str = 'worker',
                   time_of_day: str = 'morning',
                   language: str = 'en',
                   emoji_enabled: bool = True) -> Dict[str, Any]:
    """
    Select and customize a message based on all contextual parameters.
    
    Returns a dict with:
    - text: The final message text
    - category: The message category
    - emotional_prefix: Any emotional prefix applied
    - emoji_used: List of emojis inserted
    - formality_level: Computed formality
    """
    messages = MESSAGE_CATEGORIES.get(category, MESSAGE_CATEGORIES['routine_check'])
    base_msg = rng.choice(messages)
    
    # Template substitution
    if context:
        base_msg = base_msg.replace('{asset}', str(context.get('asset', '44A')))
        base_msg = base_msg.replace('{temp}', str(context.get('temp', '??')))
        base_msg = base_msg.replace('{vib}', str(context.get('vib', '??')))
        base_msg = base_msg.replace('{press}', str(context.get('press', '??')))
        base_msg = base_msg.replace('{area}', str(context.get('area', 'block-A')))
        base_msg = base_msg.replace('{harm}', str(context.get('harm', '??')))
        base_msg = base_msg.replace('{ambient}', str(context.get('ambient', '32')))
        base_msg = base_msg.replace('{incoming}', str(context.get('incoming', 'next shift')))
        base_msg = base_msg.replace('{n}', str(context.get('n', '5')))
    
    # Emotional prefix
    prefix = ''
    if emotional_state in EMOTIONAL_PREFIXES:
        if rng.random() < 0.6:  # 60% chance of emotional prefix
            prefix = rng.choice(EMOTIONAL_PREFIXES[emotional_state]) + ' '
    
    # Emoji insertion (role-dependent frequency)
    emojis_used = []
    role_config = ROLE_FORMALITY.get(role_level, ROLE_FORMALITY['worker'])
    if emoji_enabled and rng.random() < role_config['emoji_rate'] * 3:
        # Select contextually appropriate emoji
        if 'fire' in base_msg or 'emergency' in base_msg.lower():
            emoji_pool = INDUSTRIAL_EMOJIS['fire'] + INDUSTRIAL_EMOJIS['alert']
        elif 'ok' in base_msg or 'normal' in base_msg or 'clear' in base_msg:
            emoji_pool = INDUSTRIAL_EMOJIS['ok']
        elif 'temp' in base_msg or 'heat' in base_msg:
            emoji_pool = INDUSTRIAL_EMOJIS['temperature']
        elif 'safe' in base_msg.lower():
            emoji_pool = INDUSTRIAL_EMOJIS['safety']
        else:
            emoji_pool = INDUSTRIAL_EMOJIS['communication']
        
        emoji = rng.choice(emoji_pool)
        emojis_used.append(emoji)
        # Add emoji at end (most common in real chats)
        base_msg = base_msg + ' ' + emoji
    
    final_msg = prefix + base_msg
    
    return {
        'text': final_msg,
        'category': category,
        'emotional_prefix': prefix.strip(),
        'emoji_used': emojis_used,
        'formality_level': role_config['formality'],
    }



# ============================================================================
# ADDITIONAL CATEGORIES TO REACH 1000+ (20 more categories x 20 msgs each)
# ============================================================================

MESSAGE_CATEGORIES.update({
    'inventory_logistics': [
        "spare bearing arrived from warehouse collecting now",
        "coupling rubber element stock zero need emergency purchase",
        "oil filter stock running low only 2 left order more",
        "stores closed today weekend emergency key with security",
        "crane sling certification expired cannot use until recertified",
        "PPE stock low safety shoes size 9 out of stock",
        "welding rod consumption high this month check wastage",
        "diesel tank 30pct need refilling before monday",
        "chemical drum delivery expected today clear storage space",
        "tools missing from workshop investigate and report",
        "imported spare stuck in customs follow up with procurement",
        "scrap yard full need clearance drive organize sale",
        "oil drum leaking in storage area containment needed",
        "gasket material received wrong spec returning to vendor",
        "test equipment calibration due send to agency this week",
        "hydraulic oil contaminated entire batch rejected sampling more",
        "forklift needs fuel diesel tank locked call store keeper",
        "new PPE batch received distribute to all shifts",
        "critical spare inventory audit due this week count everything",
        "generator fuel consumption increased check for leaks",
    ],
    'environmental_compliance': [
        "stack emission monitoring due this week arrange contractor",
        "effluent treatment plant pH drifting high adjust dosing",
        "noise survey required for new equipment installation",
        "hazardous waste manifest pending sign off from environment officer",
        "air quality monitoring station showing spike investigating",
        "water consumption exceeded quota this month find savings",
        "oil spill near transformer contained and cleaned up",
        "PCB inventory declaration due to pollution board submit",
        "green belt area maintenance overdue contractor contacted",
        "energy audit recommendation implementation pending 3 items",
        "carbon footprint reporting data collection reminder",
        "rainwater harvesting system blocked cleaning needed",
        "used oil collection for recycling due arrange pickup",
        "environmental clearance renewal application submitted",
        "solar panel cleaning due output dropped 15pct",
        "zero liquid discharge system performance declining troubleshoot",
        "fly ash utilization below target liaise with cement plant",
        "noise barrier installation pending for residential side",
        "chemical storage segregation audit finding still open",
        "biodiversity survey of plant area required for report",
    ],
    'electrical_specific': [
        "power factor dropped below 0.85 capacitor bank issue check",
        "cable joint temperature high on 11kV feeder monitoring",
        "earth resistance test annual results slightly high at bus B",
        "relay coordination study needed new transformer changes settings",
        "harmonic filter not working THD increasing on bus",
        "VFD drive showing overload fault on pump {asset} resetting",
        "transformer oil BDV test due sample collected sending to lab",
        "HT switchgear mechanism needs greasing planned for next shutdown",
        "battery charger alarm float voltage fluctuating",
        "power cable laying route finalized for new project confirm",
        "DG set parallel operation issue auto synchronization failing",
        "lightning arrester leakage current increasing replace proactively",
        "busbar joint heating found during thermography schedule repair",
        "motor winding resistance test shows imbalance investigate",
        "current transformer ratio error found during calibration",
        "solar inverter tripping frequently on high DC voltage",
        "cable tray overloaded in {area} reroute new cables elsewhere",
        "emergency lighting battery backup test failed in {area}",
        "electrical earthing pit condition deteriorated needs refilling",
        "arc flash study results posted follow new PPE requirements",
    ],
})


MESSAGE_CATEGORIES.update({
    'instrumentation_control': [
        "PID loop oscillating on FCV-101 needs retuning",
        "thermocouple TC-44A showing open circuit replace",
        "pressure transmitter PT-201 drift calibration needed",
        "control valve positioner feedback lost check 4-20mA signal",
        "DCS I/O card failure channel 12 redundant card active",
        "field bus communication error intermittent check junction box",
        "safety system partial stroke test due schedule it",
        "RTD vs thermocouple discrepancy 2 degree investigate",
        "trip tested successfully response time within spec",
        "new instrument air regulator installed filter replaced",
        "HART communication lost with level transmitter check wiring",
        "control room HMI screen refresh slow DCS server load high",
        "analyzer shelter AC failed sample conditioning impacted",
        "flow meter showing negative reading probably air pocket",
        "final control element stuck partially need stroking",
        "cascade control not stabilizing master loop too aggressive",
        "ratio control drifting product quality impacted adjust setpoint",
        "emergency shutdown logic test satisfactory all voted correctly",
        "SIS proof test overdue by 2 weeks schedule immediately",
        "smart transmitter diagnostics showing sensor degradation warning",
    ],
    'mechanical_specific': [
        "pump mechanical seal leaking replace during next opportunity",
        "coupling alignment laser results within tolerance documenting",
        "gearbox oil level low top up before next shift",
        "bearing replacement complete initial vibration readings low",
        "fan blade crack detected during inspection order replacement",
        "belt tension adjustment needed on cooling tower fan",
        "valve stem packing leak minor tightening attempted improved",
        "pipe wall thickness scan shows 20pct loss at elbow",
        "expansion joint bellows showing fatigue cracks plan replacement",
        "agitator shaft seal replaced trial run successful",
        "compressor valve plate worn knocking noise on discharge",
        "turbine blade erosion noted during borescope inspection",
        "conveyor belt splice failing replace during next shutdown",
        "hydraulic cylinder rod scratched seal replacement needed",
        "structural steel corrosion under insulation CUI found during inspection",
        "flange bolt torque check completed all within specification",
        "pump impeller clearance out of spec performance degraded",
        "cooling tower fill material deteriorated replacement quoted",
        "diesel engine injector nozzle blocked cleaning attempted",
        "crane wire rope inspection 3 broken wires approaching rejection",
    ],
    'shift_report_formal': [
        "Shift Report: All units operating at rated capacity. No trips. No alarms pending.",
        "Shift Summary: One alarm on {asset} at 0300hrs. Investigated. Sensor drift. Cleared.",
        "Daily Log: Production target met. Efficiency 96.2pct. One maintenance activity completed.",
        "Shift Handover Note: All permits closed. No outstanding isolation. Logbook signed.",
        "Operational Report: Grid frequency stable. Generation at 480MW. Coal stock 7 days.",
        "End of Shift: All parameters within normal operating envelope. Next round scheduled 2hrs.",
        "Night Shift Report: Quiet night. One false alarm at 0145hrs. No interventions.",
        "Shift Performance: Availability 100pct. No forced outage. Heat rate 2340 kcal/kWh.",
        "Duty Report: Water chemistry within limits. One blowdown conducted as per schedule.",
        "Control Room Log: DCS healthy. All redundancy active. Historian recording normally.",
        "Shift Close: Tool count matched. All lockouts released. Area housekeeping completed.",
        "Production Summary: Batch 47 completed. Quality approved. Packing commenced.",
        "Operations Diary: Startup of Unit-2 completed at 1400hrs. Synchronized at 1430hrs.",
        "Status Report: Shutdown unit-3 maintenance ongoing. Expected return to service 72hrs.",
        "Incident Report: Minor oil spill at pump 44A. Contained. Cleaned. Report filed.",
        "Daily Briefing Notes: Safety topic covered. Attendance 34/36. Two on leave.",
        "Morning Report to Management: All KPIs green. No environmental exceedances.",
        "Weekly Summary: 3 breakdowns total. MTBF improved vs last month. Reliability 98.7pct.",
        "Monthly Close: Production exceeded target by 3pct. Best month this quarter.",
        "Quarterly Review Input: Maintenance cost within budget. Spare consumption normal.",
    ],
    'inter_department': [
        "maintenance please send team for {asset} bearing issue urgent",
        "stores can you check if we have seal kit for {asset} in stock",
        "electrical team high voltage permit needed for {area} work",
        "quality lab please collect sample from tank 3 for testing",
        "safety team please inspect scaffolding in {area} before work resumes",
        "planning team when is next shutdown window for {asset} available",
        "procurement urgent indent raised for {asset} seal please expedite",
        "HR requesting headcount details for next shift roster planning",
        "IT team DCS backup server showing error please check",
        "transport please arrange vehicle for vendor pickup from airport",
        "civil team manhole cover broken in {area} safety hazard fix urgent",
        "environment team effluent sample results needed for monthly report",
        "instrumentation team control valve not responding need attention",
        "finance team overtime hours submitted for approval this month",
        "training coordinator certification renewal list shared please confirm dates",
        "security team suspicious vehicle near boundary check CCTV",
        "medical team one person feeling dizzy in {area} please attend",
        "canteen management tea break timing request from night shift",
        "fire team annual inspection of hydrant system due this week",
        "admin team notice board update needed old circulars still displayed",
    ],
    'operator_decision': [
        "reducing load on {asset} to 80pct as precaution until investigated",
        "switching to standby pump proactively while main pump checked",
        "increasing monitoring frequency to every 5 minutes for {asset}",
        "activating manual control override on {asset} control valve",
        "requesting maintenance callback on {asset} condition worsening",
        "extending shift handover by 30min to monitor developing situation",
        "starting auxiliary cooling system as additional precaution",
        "reducing process throughput to decrease thermal load",
        "isolating suspect sensor and relying on redundant channel",
        "calling supervisor to site for decision on potential trip",
        "bypassing alarm temporarily while investigating root cause",
        "opening additional cooling water valve to reduce temperature",
        "throttling discharge valve to reduce pump cavitation risk",
        "starting backup lubrication pump as precaution oil pressure low",
        "placing {asset} on enhanced monitoring 15 min intervals",
        "deferring non-essential maintenance to focus on developing issue",
        "alerting incoming shift of situation for seamless transition",
        "documenting all readings in logbook every 5 minutes now",
        "requesting vibration specialist for expert analysis today",
        "consulting manufacturer manual for recommended action at this condition",
    ],
    'cross_shift_callback': [
        "following up on last shift issue with {asset} check what happened",
        "yesterday vibration was high did night shift notice anything",
        "maintenance was supposed to attend during B shift did they come",
        "referring to logbook entry page 42 same issue recurring",
        "third time this week same alarm something systemic going on",
        "last month we had similar situation on sister unit what was done",
        "checking if previous shift action resolved the drift or not",
        "night shift left note about unusual noise investigating now",
        "continuing monitoring started by previous shift trend unchanged",
        "spare ordered yesterday has it arrived check with stores",
        "vendor visit was scheduled for today confirm timing with planning",
        "following up on work order raised 3 days ago status update needed",
        "same thermocouple flagged by last shift recalibrating now",
        "continuing from previous shift handover note on {asset} condition",
        "last shift did partial maintenance completion pending this shift",
        "escalation raised yesterday to management any response received",
        "pump that tripped last shift has it been investigated root cause",
        "following safety observation raised by C shift about {area}",
        "contractor work that started last shift how much completed",
        "relay that operated last night cause identified and documented",
    ],
})


MESSAGE_CATEGORIES.update({
    'emergency_response': [
        "fire brigade notified ETA 8 minutes",
        "assembly point headcount in progress all sections reporting",
        "emergency controller taking charge all teams report status",
        "ambulance requested for injured personnel ETA 12 min",
        "mutual aid triggered neighboring plant sending foam tender",
        "media inquiry expected corporate communications alerted",
        "regulatory authority notification mandatory filing now",
        "family notification protocol activated for injured personnel",
        "incident command post established at gate 1 parking",
        "all non-essential personnel asked to leave site immediately",
        "secondary hazard assessment ongoing checking for toxic release",
        "rescue team deployed with BA sets to affected area",
        "helicopter landing zone being cleared just in case",
        "blood bank contacted O negative and A positive needed",
        "insurance company emergency helpline called claim number noted",
        "post incident security cordon established no photos allowed",
        "crisis communication team assembling draft statement needed",
        "regulatory inspector arriving ensure all documentation ready",
        "employee assistance program activated counseling available",
        "investigation team formed preservation of evidence ordered",
    ],
    'startup_shutdown': [
        "pre-startup checklist in progress item 12 of 45 completed",
        "lube oil system primed and circulating pressure building up",
        "turning gear engaged shaft rotating at 3 rpm warming up",
        "steam parameters approaching startup values pressure 42 bar",
        "synchronization preparation checking voltage matching",
        "loading at 10pct steps every 15 minutes as per SOP",
        "initial vibration readings post startup all within limits",
        "bearing temperature stabilizing after startup typical transient",
        "trip system armed and functional startup interlock cleared",
        "startup notification sent to grid operator and dispatch",
        "controlled shutdown initiated unloading at 5pct per minute",
        "generator breaker opened unit isolated from grid safely",
        "cool down in progress maintaining aux systems for 4 hours",
        "post shutdown inspection walkthrough scheduled for tomorrow",
        "preservation activities needed if shutdown exceeds 7 days",
        "startup oil pump running confirming bearing oil supply",
        "hydrogen seal oil system checked before turbine excitation",
        "boiler light up sequence initiated burner management active",
        "condenser vacuum building up startup ejector in service",
        "auxiliary power changeover to station transformer completed",
    ],
    'performance_monitoring': [
        "heat rate this hour 2380 kcal target 2350 slightly above",
        "turbine efficiency 88.2pct down from 89.1pct last week investigate",
        "condenser TTD increased to 5.2C tube fouling suspected",
        "auxiliary power consumption 8.3pct of generation above benchmark",
        "coal consumption 0.62 kg per kWh target 0.59 excess usage",
        "plant load factor for month 87pct target 90pct gap to close",
        "specific oil consumption trending up motor condition check",
        "boiler efficiency dropped by 0.5pct unburnt carbon in ash high",
        "cooling tower approach temperature 8C design is 5C degraded",
        "compressor specific power higher than design fouling likely",
        "pump efficiency test shows 72pct vs design 82pct wear suspected",
        "transformer losses measured higher than factory test values",
        "DG fuel consumption higher than rated investigate governor",
        "chiller COP dropped from 5.2 to 4.8 refrigerant charge check",
        "steam trap survey completed 12 of 200 traps failed replace",
        "vacuum system performance degraded air inleakage test needed",
        "feed water heater TTD increased tube leak possible",
        "ash handling system capacity underperforming clinker formation",
        "demineralization plant output below rated flow resin exhausted",
        "instrument air dew point minus 20C acceptable within spec",
    ],
    'regulatory_audit': [
        "factory inspector visit confirmed for next tuesday prepare all registers",
        "electrical inspector test certificates to be renewed",
        "pressure vessel inspection due next month prepare documentation",
        "environmental consent renewal application filed awaiting",
        "PESO license for compressed gas storage expiring renew",
        "fire NOC renewal inspection scheduled cooperate fully",
        "labour welfare officer visit expected maintain records updated",
        "pollution board surprise inspection possible keep compliant always",
        "chief electrical inspector approval needed for HT installation",
        "IBR inspection of boiler due prepare boiler logbook and drawings",
        "AERB regulatory inspection for radiation sources verification",
        "building stability certificate renewal structural audit needed",
        "weights and measures inspector calibration verification",
        "drug inspector audit for pharmaceutical raw materials storage",
        "customs bonded warehouse audit inventory reconciliation needed",
        "quality auditor from customer arriving observe process",
        "ISO surveillance audit next month internal audit to be completed first",
        "OHSAS certification renewal transition to ISO 45001 planned",
        "food safety audit for canteen operation FSSAI compliance",
        "trade effluent consent conditions review ensure we meet all",
    ],
    'career_progression': [
        "congratulations on promotion well deserved keep it up",
        "interview panel results announced check notice board",
        "skill assessment test scheduled for all technicians next month",
        "lateral transfer opportunity announced who is interested",
        "departmental exam results out 8 of 12 passed congratulations",
        "management trainee batch posting orders issued report monday",
        "voluntary retirement scheme announced details with HR",
        "promotion committee meeting next week submit recommendations",
        "performance bonus declared this quarter good work everyone",
        "overseas posting opportunity for 2 years interested apply",
        "acting charge given to senior most available for leave period",
        "additional charge of safety department given to operations head",
        "new designation approved by board for specialized roles",
        "training completion certificate needed for next promotion eligibility",
        "senior operator exam clearing is mandatory for supervisor grade",
        "experience certificate requested by employee for personal records",
        "relieving letter issued for transferred employee formalities done",
        "new reporting structure effective from next month updated chart shared",
        "mentorship program pairing announced check assignment list",
        "succession planning discussion keep confidential only for HODs",
    ],
    'morale_team_building': [
        "team lunch organized this friday everyone join",
        "birthday celebration at 1530hrs in break room cake cutting",
        "cricket match against maintenance team this saturday 0700hrs",
        "team building activity planned next month outstation trip",
        "recognition award for best safety performance this quarter team A",
        "farewell function for retiring colleague thursday evening attend",
        "family day event planning committee nominations open",
        "suggestion scheme winner announced prize giving tomorrow",
        "marathon participation company sponsoring registration",
        "blood donation camp next week volunteers please register",
        "yoga session starting daily 0630hrs interested join",
        "photography contest theme industrial beauty entries by month end",
        "cultural program practice starting for annual day auditions open",
        "gym membership subsidized by company enroll at HR office",
        "stress management workshop by external consultant next wednesday",
        "team dinner planned for project completion everyone deserves it",
        "employee of month selection inputs from all supervisors needed",
        "charity drive collection for local school donate books and clothes",
        "retirement gift fund collection for 3 retiring this month",
        "new employee welcome note added to group introduce yourself",
    ],
})


MESSAGE_CATEGORIES.update({
    'process_chemistry': [
        "pH drifting high on neutralization tank adjust acid dosing",
        "dissolved oxygen reading 6.2 ppm slightly above set point",
        "catalyst bed pressure drop increasing regeneration needed soon",
        "reactor temperature profile uneven check distributor plate",
        "crystallization batch showing unexpected color investigate",
        "distillation column reflux ratio needs adjustment product off spec",
        "polymer viscosity lower than target molecular weight issue",
        "exothermic reaction temperature rising faster than expected",
        "solvent recovery rate dropped check condenser performance",
        "raw material moisture content high affecting reaction yield",
        "batch reaction time exceeded by 45 min kinetics slower today",
        "waste stream COD higher than permit limit treatment adjustment needed",
        "chlorine residual in cooling water below minimum redose",
        "boiler feed water hardness increased check softener regeneration",
        "fuel oil viscosity high heating needed before atomization",
        "lime slurry preparation tank level low prepare fresh batch",
        "hydrogen purity analyzer reading low purge and recalibrate",
        "ammonia slip from SCR increasing catalyst may be degrading",
        "carbon bed breakthrough detected regenerate or replace",
        "resin exhaustion indicated by conductivity spike regenerate softener",
    ],
    'communication_breakdown': [
        "radio battery dead borrowing spare from security",
        "PA system not audible in {area} speaker damaged",
        "phone network down using WhatsApp for all comm now",
        "DCS intercom channel 3 static cant hear field clearly",
        "walkie talkie channel congested too many people on same freq",
        "email server down urgent notices going through WhatsApp only",
        "CCTV monitor in control room blank losing visual of {area}",
        "satellite phone needed cell tower maintenance this area",
        "siren test showed zone 4 not audible investigate",
        "electronic noticeboard malfunction paper notices posted instead",
        "video conference system not connecting IT please fix urgent",
        "shift report system offline submitting by email as backup",
        "access card reader malfunction at gate 3 manual entry log",
        "fire alarm panel showing comm fault to zone 7 investigate",
        "telemetry link to remote station intermittent check antenna",
        "gas detector wireless link lost for 15 min now restored",
        "SCADA historian communication drop 5 min data gap recorded",
        "printer in control room jammed need to print emergency procedure",
        "paging system only reaching 60pct of plant expand coverage",
        "emergency phone in {area} vandalized repair urgently needed",
    ],
    'cultural_celebration': [
        "diwali bonus distributed happy diwali everyone stay safe",
        "eid mubarak to all may this bring prosperity and peace",
        "christmas party arrangements ongoing tree in lobby looks great",
        "pongal celebrations tomorrow kolam competition at gate",
        "republic day flag hoisting 0800hrs sharp attendance mandatory",
        "independence day celebration chief guest arriving 0900hrs",
        "onam sadya organized by south indian association enjoy lunch",
        "holi colour play restricted to designated area only safety first",
        "christmas eve no work past 1800hrs management approved",
        "new year resolution board put up in canteen write yours",
        "ramadan kareem adjusted meal timings posted in canteen",
        "bathukamma flower decoration competition by ladies forum",
        "navratri garba night organized saturday at community hall",
        "founders day celebration next week volunteer for coordination",
        "women's day event panel discussion on workplace equality",
        "earth day plantation drive 50 saplings target participate",
        "world safety day pledge ceremony and walkathon 0700hrs",
        "engineers day quiz competition technical team register",
        "children's day essay competition for employees kids submit by friday",
        "annual day practice rehearsal daily 1800-1900hrs auditorium",
    ],
    'health_medical': [
        "first aid applied minor cut on hand worker continuing work",
        "heat stroke symptoms reported worker moved to shade hydrating",
        "annual medical checkup results normal for most team members",
        "eye irritation reported in {area} dust check ventilation",
        "back pain complaint from worker heavy lifting without support",
        "audiometry test shows hearing threshold shift for 3 operators",
        "mosquito breeding spotted near water tank fogging requested",
        "food poisoning 4 cases from canteen yesterday investigating",
        "stress counseling session available this week register with HR",
        "BMI screening results average team needs fitness improvement",
        "chemical splash minor no injury safety shower used immediately",
        "fatigue related near miss operator almost tripped on stairs",
        "dehydration risk high today ensure water bottles filled",
        "lung function test abnormal for welder medical follow up needed",
        "vaccination drive next week tetanus and hepatitis B boosters",
        "ergonomic assessment done for control room chair replacement approved",
        "mental health awareness poster campaign starting this month",
        "occupational health center pharmacy stock running low reorder",
        "pre employment medical for 8 new joiners scheduled tomorrow",
        "medical insurance card distribution new policy details shared",
    ],
    'financial_commercial': [
        "electricity sold to grid today revenue 45 lakhs good day",
        "fuel cost per unit increased raw material price impact",
        "budget variance report shows overspend on maintenance explain",
        "working capital tight vendor payments delayed inform them",
        "insurance claim filed for transformer failure documentation pending",
        "energy trading opportunity spot price high maximize generation",
        "penalty notice from grid operator for frequency deviation",
        "cost reduction idea saves 12 lakhs per month implementation approved",
        "carbon credit registration in progress expected revenue next year",
        "commercial department asking for generation forecast next week",
        "spare parts cost this quarter 18pct over budget analyze",
        "contractor billing dispute 3 months pending resolve urgently",
        "LD clause activated against vendor for late delivery recovery",
        "ash revenue from cement plant contributes to bottom line",
        "water cess payment due this quarter accounts preparing cheque",
        "scrap auction completed revenue 8.5 lakhs credited to account",
        "energy audit identified 14 lakh annual savings implement actions",
        "overtime bill for this month unusually high justify department wise",
        "capital expenditure proposal for new pump submitted to board",
        "depreciation schedule updated for newly capitalized assets",
    ],
})


MESSAGE_CATEGORIES.update({
    'contractor_safety_violation': [
        "contractor working at height without harness STOP WORK immediately",
        "hot work near flammable storage contractor didnt check permit",
        "contractor team entered confined space without gas test violation",
        "grinding without face shield contractor worker warned twice already",
        "scaffolding erected without inspection tag contractor to remove",
        "contractor vehicle speeding inside plant gate warned and warned",
        "electrical work by contractor without LOTO clear violation reported",
        "contractor using damaged sling for lifting STOP immediately",
        "welding sparks falling on cable tray below fire watch absent violation",
        "contractor smoking near hazardous area ejected from site today",
    ],
    'planning_scheduling': [
        "next week shutdown schedule released 47 jobs approved priority 1",
        "critical path item bearing replacement delay pushes everything",
        "resource conflict mechanical team needed at 2 places simultaneously",
        "outage window reduced from 72hrs to 48hrs reschedule jobs",
        "shutdown postponed by management production priority revised plan",
        "material not delivered shutdown start date at risk inform management",
        "manpower availability confirmed 45 maintenance plus 30 contractors",
        "pre-shutdown isolation list prepared 23 isolations needed",
        "shutdown daily meeting 0700hrs progress review all leads attend",
        "punch list items 12 remaining 3 days left to complete all",
    ],
    'it_systems': [
        "DCS server CPU at 95pct slowness reported killing unnecessary processes",
        "historian disk full automatic purge triggered 30 days retained",
        "firewall rule change needed for new SCADA connection raise request",
        "antivirus update caused DCS workstation crash rolling back",
        "network switch failure OT network switch to backup path active",
        "cyber security patch pending for DCS approval from OEM awaited",
        "USB port violation detected in control room investigate who and why",
        "backup tape rotation completed offsite courier picked up",
        "SCADA software license expiring next month renewal in progress",
        "remote access VPN not connecting vendor support impacted call IT",
    ],
    'legacy_knowledge': [
        "this pump designed in 1987 original drawings in plan room cabinet 3",
        "factory manual says clearance 0.05mm but we always set 0.08 works better",
        "old timer told me this valve sticks every summer lubricate end of may",
        "original commissioning team set this parameter nobody knows why this value",
        "this bypass was added after 1995 incident never documented properly",
        "vendor company no longer exists for this machine spare sourcing problem",
        "foundation design for this machine was modified during 2003 revamp",
        "control logic was changed 5 times finding latest version is challenge",
        "cable routing for this area was done before CAD era no drawings exist",
        "previous plant head insisted on this arrangement nobody dares to change",
    ],
    'whistleblower_ethics': [
        "noticed safety report numbers dont match actual incidents reporting up",
        "overtime records being manipulated someone is ghost signing",
        "maintenance record says replaced but physically old part still there",
        "environmental readings possibly tampered reporting concerns to management",
        "noticed unsafe practice tolerated because supervisor is involved difficult",
        "quality results backdated for expired batch raising concern formally",
        "training records show people attended but they were actually absent",
        "stock register discrepancy between system and physical count flagging",
        "incident was underreported to avoid regulatory scrutiny not comfortable with this",
        "vendor billing for work not actually completed evidence collected reporting",
    ],
})


MESSAGE_CATEGORIES.update({
    'emergency_drill_exercise': [
        "THIS IS A DRILL fire alarm test zone 3 do NOT evacuate",
        "mock drill starting 1400hrs treat as real follow all procedures",
        "drill results: muster time 4min23sec target was 3min need improvement",
        "observer noted 3 employees walking not running during drill",
        "drill scenario was chemical leak good response by emergency team",
        "lessons from drill: PA system volume inadequate in {area}",
        "drill postponed due to actual operational issue reschedule next week",
        "external agency evaluating our drill performance today best behavior",
        "monthly fire pump auto start drill conducted successfully",
        "emergency shutdown drill completed all interlocks functioned correctly",
        "rescue team response time 2min15sec within target well done",
        "drill feedback: first aid kit at assembly point was missing items",
        "communication during drill was poor radio discipline needed",
        "drill certificates issued to all participants add to training records",
        "next drill scenario will be earthquake response prepare accordingly",
        "night shift drill results significantly worse than day shift why",
        "contractor participation in drill was poor include in next time",
        "ambulance response simulation test ETA realistic confirmed",
        "drill cost estimate for external fire brigade participation submitted",
        "video recording of drill available for training purposes watch it",
    ],
    'personal_life_spillover': [
        "sorry running late kid was sick morning school issue",
        "need to leave 30min early today family emergency",
        "wife calling hospital appointment need to take this call",
        "distracted today mother in law health not good worried",
        "happy today daughter results came topped the class proud",
        "exhausted yesterday was house shifting no sleep at all",
        "stressed about home loan EMI increase affecting focus sorry",
        "marriage anniversary forgot need to buy something during break",
        "kid won inter school competition treating everyone chai today",
        "father retired today feeling emotional about old generation leaving",
        "traffic accident near home nobody hurt but shaken up",
        "house construction going on contractors calling every hour annoying",
        "college admission stress for son please bear with me today",
        "water problem in colony third day no supply frustrating morning start",
        "new bike purchased feeling happy riding today first time",
    ],
})



# Top up final category to cross 1000
MESSAGE_CATEGORIES['routine_check'].extend([
    "night round complete all secure perimeter check done",
    "cooling system nominal flow rates stable pump running smooth",
    "auxiliary systems check complete boiler feed pumps both healthy",
    "area inspection done housekeeping acceptable no slip hazards found",
    "fire protection system healthy all deluge valves in position",
    "instrument air quality acceptable dew point within limits",
])
