"""
Multilingual Workplace Phrases — 40+ languages.
Realistic industrial/workplace communication fragments.
Each language has 15-25 everyday workplace phrases that
workers would actually say in that language.

These are NOT translations — they're natural expressions
a native speaker would use at work, including slang,
informal grammar, and cultural expressions.
"""

WORKPLACE_PHRASES = {
    # ═══════════════════════════════════════
    # SOUTH ASIAN (major industrial workforce)
    # ═══════════════════════════════════════
    "en": [
        "check the pressure readings on tank 3",
        "morning shift starting, all clear",
        "need to replace the gasket before lunch",
        "who took the torque wrench from bay 2?",
        "supervisor wants the report by end of day",
        "production target is 500 units today",
        "the new guy is learning fast",
        "oil temperature looks high, keep an eye",
        "break time, anyone want tea?",
        "safety meeting at 10am don't forget",
        "night shift handover: pump B making noise",
        "delivery truck arrived gate 3",
        "quality rejected batch 47, recheck specs",
        "happy birthday boss, cake in canteen",
        "overtime approved for weekend",
        "can someone cover my shift tomorrow?",
        "this machine has been acting up all week",
        "did you see the new circular from HR?",
        "maintenance team is running behind schedule",
        "let me show you how to do this properly",
        "we need to order more raw material ASAP",
        "good job on yesterday's output, team",
        "careful with that, it's still hot",
        "where's the spare key for the tool room?",
        "I think we should report this to safety",
    ],
    "te": [
        "tank 3 pressure chudandi, ekkuva undi",
        "morning shift start ayyindi, anni clear",
        "lunch loapala gasket marchcheyali",
        "bay 2 nunchi torque wrench evaru teesaru?",
        "supervisor report today loapala kavali annadu",
        "ee roju target 500 units",
        "kotha abbai baaga nerchukuntunaadu",
        "oil temperature ekkuva undi, chustu undandi",
        "break time, chai kaavala evariki?",
        "10 ki safety meeting, marchipokandi",
        "night shift handover: pump B sound vastondi",
        "delivery truck gate 3 lo vachindi",
        "quality batch 47 reject chesindi, specs check cheyyandi",
        "boss ki happy birthday, canteen lo cake undi",
        "weekend overtime approve ayyindi",
        "repu naa shift cover chesthaara evaru?",
        "ee machine vaaram antha problem isthondi",
        "HR circular chuusaara kotha di?",
        "maintenance team late avuthondi",
        "nenu chepthaa, ilaa cheyyali chudu",
        "raw material urgent ga order cheyali",
        "ninna output baagundi team, keep it up",
        "jaagrattha, inka hot ga undi adi",
    ],
    "hi": [
        "tank 3 ka pressure check karo, zyada hai",
        "morning shift shuru, sab clear hai",
        "lunch se pehle gasket badalna hai",
        "bay 2 se torque wrench kisne liya?",
        "supervisor ne bola report aaj shaam tak chahiye",
        "aaj ka target 500 units hai",
        "naya ladka jaldi seekh raha hai",
        "oil temperature zyada dikh raha hai, dhyan rakho",
        "break time, chai chahiye kisko?",
        "10 baje safety meeting hai, bhoolna mat",
        "night shift handover: pump B mein awaaz aa rahi",
        "delivery truck gate 3 pe aaya",
        "quality ne batch 47 reject kiya, specs dubara check karo",
        "boss ko happy birthday, canteen mein cake hai",
        "weekend overtime approved hai",
        "kal meri shift cover karega koi?",
        "ye machine poore hafte se problem de rahi hai",
        "HR ka naya circular dekha?",
        "maintenance wale late ho rahe hain",
        "aao, main dikhata hoon kaise karna hai",
        "raw material urgent order karna padega",
        "kal ka output accha tha, keep it up team",
        "sambhal ke, abhi bhi garam hai",
    ],
    "ta": [
        "tank 3 pressure parunga, adhigama irukku",
        "morning shift start aachu, ellam clear",
        "lunch ku munna gasket maathanum",
        "bay 2 la irundhu torque wrench yaar eduthaanga?",
        "supervisor report inniki venumnu solraar",
        "inniki target 500 units",
        "pudhu paiyan seekirama kathukuraan",
        "oil temperature adhigama irukku, kavanama parunga",
        "break time, yaaaruku tea venum?",
        "10 maniku safety meeting, marakaadheenga",
        "night shift handover: pump B la sound varuthhu",
        "delivery truck gate 3 la vandhuruchu",
        "quality batch 47 reject panniruchu, specs parunga",
        "boss ku happy birthday, canteen la cake irukku",
        "weekend overtime approve aachu",
        "naalaikku yaaraavathu ennoda shift paappaangala?",
        "indha machine oru vaaram aagi problem kudukkuthu",
    ],
    "kn": [
        "tank 3 pressure nodri, jasti ide",
        "morning shift start aaytu, ella clear",
        "lunch munche gasket badlisi",
        "bay 2 inda torque wrench yaaru togondru?",
        "supervisor report indu beku anta heldru",
        "ivattu target 500 units",
        "hosa huduga bega kalthkontidhane",
        "oil temperature jasti ide, nodi irri",
        "break time, yarigaadru chai beka?",
        "10 ghantege safety meeting, mariyabedi",
        "night shift handover: pump B shabda bartide",
        "delivery truck gate 3 alli bantu",
    ],
    "ml": [
        "tank 3 pressure nokkoo, kooduthal aanu",
        "morning shift thudangi, ellam clear aanu",
        "lunch nu munpe gasket maattanam",
        "bay 2 il ninnu torque wrench aaraa eduthu?",
        "supervisor parayunnu report innu vendi enn",
        "innatte target 500 units aanu",
        "pudhiya paiyan vegam padikkunnundu",
        "oil temperature koodi, sookshikkoo",
        "break time, aarkkenkkilum chaaya veno?",
        "10 manikku safety meeting, marakkaruthu",
    ],
    "bn": [
        "tank 3 er pressure check koro, beshi ache",
        "morning shift shuru hoyeche, sob clear",
        "lunch er aage gasket bodlate hobe",
        "bay 2 theke torque wrench ke niyeche?",
        "supervisor report aaj er modhdhey chai bolechhe",
        "aajker target 500 units",
        "notun chele tara tari shikhche",
        "oil temperature beshi dekhachhe, nojor rakho",
        "break time, karo cha chai?",
        "10 tay safety meeting, bhulona",
        "night shift handover: pump B te awaj ashche",
        "delivery truck gate 3 te esheche",
    ],
    "ur": [
        "tank 3 ka pressure check karo, zyada hai",
        "morning shift shuru ho gaya, sab theek",
        "lunch se pehle gasket badalna hai",
        "bay 2 se torque wrench kisne liya?",
        "supervisor ne report aaj chahiye bola",
        "aaj ka target 500 units hai",
        "naya banda jaldi seekh raha hai",
        "oil temperature zyada hai, dekhte raho",
        "break time, chai chahiye kisko?",
        "das baje safety meeting hai, yaad rakhna",
    ],
    # ═══════════════════════════════════════
    # MIDDLE EAST & NORTH AFRICA
    # ═══════════════════════════════════════
    "ar": [
        "افحص ضغط الخزان 3، مرتفع",
        "بداية وردية الصباح، كل شيء واضح",
        "لازم نغير الحشية قبل الغداء",
        "مين أخذ مفتاح العزم من المنطقة 2؟",
        "المشرف يبي التقرير قبل نهاية اليوم",
        "هدف اليوم 500 وحدة",
        "الموظف الجديد يتعلم بسرعة",
        "حرارة الزيت مرتفعة، خلوا بالكم",
        "وقت الاستراحة، أحد يبي شاي؟",
        "اجتماع السلامة الساعة 10، لا تنسون",
        "خلصت الوردية، كل شي تمام",
        "الشحنة وصلت البوابة 3",
        "الجودة رفضت دفعة 47",
        "مبروك يا بوس، كيكة بالكافتيريا",
        "الاوفرتايم مقبول لنهاية الاسبوع",
    ],
    "tr": [
        "tank 3 basinci kontrol et, yuksek gorunuyor",
        "sabah vardiyasi basladi, her sey tamam",
        "ogle yemeginden once conta degistirmemiz lazim",
        "2 numarali bolumden tork anahtarini kim aldi?",
        "amir raporu gun sonuna kadar istiyor",
        "bugunun hedefi 500 birim",
        "yeni eleman hizli ogreniyor",
        "yag sicakligi yuksek gorunuyor, dikkat edin",
        "mola zamani, cay isteyen var mi?",
        "saat 10da guvenlik toplantisi, unutmayin",
        "gece vardiyasi devir teslim: pompa B ses yapiyor",
        "teslimat kamyonu kapi 3e geldi",
    ],
    "fa": [
        "فشار تانک 3 رو چک کن، بالاست",
        "شیفت صبح شروع شد، همه چیز خوبه",
        "قبل از ناهار باید واشر رو عوض کنیم",
        "کی آچار تورک رو از بخش 2 برداشته؟",
        "سرپرست گزارش رو تا آخر روز میخواد",
        "هدف امروز 500 واحده",
        "نیروی جدید داره سریع یاد میگیره",
        "دمای روغن بالاست، حواستون باشه",
        "وقت استراحته، چایی میخواین؟",
        "جلسه ایمنی ساعت 10، یادتون نره",
    ],
    # ═══════════════════════════════════════
    # SOUTHEAST ASIAN
    # ═══════════════════════════════════════
    "tl": [
        "i-check ang pressure ng tank 3, mataas",
        "simula na ng morning shift, ok na lahat",
        "kailangan palitan ang gasket bago mag-lunch",
        "sino kumuha ng torque wrench sa bay 2?",
        "sabi ng supervisor kailangan na report today",
        "target natin ngayon 500 units",
        "mabilis matuto yung bago",
        "mataas ang oil temperature, bantayan nyo",
        "break na, may gusto ba ng kape?",
        "10am safety meeting, wag kalimutan",
        "night shift turnover: may ingay sa pump B",
        "dumating na delivery truck sa gate 3",
        "reject ng quality ang batch 47, check ulit specs",
        "happy birthday boss, may cake sa canteen",
        "approved na overtime sa weekend",
    ],
    "id": [
        "cek tekanan tangki 3, tinggi banget",
        "shift pagi mulai, semua beres",
        "gasket harus diganti sebelum makan siang",
        "siapa yang ambil kunci torsi dari bay 2?",
        "supervisor minta laporan sebelum pulang",
        "target hari ini 500 unit",
        "anak baru cepat belajarnya",
        "suhu oli keliatan tinggi, pantau terus",
        "istirahat dulu, ada yang mau kopi?",
        "meeting safety jam 10, jangan lupa",
        "serah terima shift malam: pompa B berisik",
        "truk pengiriman sudah sampai gerbang 3",
    ],
    "ms": [
        "check pressure tank 3, tinggi ni",
        "shift pagi dah start, semua ok",
        "kena tukar gasket sebelum lunch",
        "sapa ambik torque wrench dari bay 2?",
        "supervisor nak report hari ni jugak",
        "target hari ni 500 unit",
        "budak baru ni cepat belajar",
        "suhu minyak nampak tinggi, monitor la",
        "break time, sapa nak teh?",
        "meeting safety pukul 10, jangan lupa",
    ],
    "vi": [
        "kiem tra ap suat be 3, cao qua",
        "ca sang bat dau roi, moi thu on",
        "phai thay gioang truoc bua trua",
        "ai lay co le luc tu bay 2?",
        "giam sat can bao cao truoc cuoi ngay",
        "muc tieu hom nay la 500 san pham",
        "nguoi moi hoc nhanh lam",
        "nhiet do dau cao, theo doi nhe",
        "nghi giai lao, ai uong tra khong?",
        "hop an toan luc 10h, dung quen",
        "ban giao ca dem: bom B co tieng la",
        "xe giao hang da den cong 3",
    ],
    "th": [
        "check ความดัน tank 3 สูงมาก",
        "กะเช้าเริ่มแล้ว ทุกอย่างโอเค",
        "ต้องเปลี่ยน gasket ก่อนกินข้าวเที่ยง",
        "ใครเอาประแจทอร์กจาก bay 2 ไป?",
        "หัวหน้าต้องการรายงานภายในวันนี้",
        "เป้าวันนี้ 500 ชิ้น",
        "คนใหม่เรียนรู้เร็วดี",
        "อุณหภูมิน้ำมันสูง ช่วยดูด้วย",
        "พัก กาแฟใครเอาบ้าง?",
        "ประชุมความปลอดภัย 10 โมง อย่าลืม",
    ],
    "my": [
        "tank 3 pressure check par, mya nay de",
        "morning shift sa par bi, a-lone a-shi par de",
        "lunch ma tot gasket hlae ya mal de",
        "bay 2 ka torque wrench be yu lar lal?",
        "supervisor report de ni tha lo chin de",
        "de ni target 500 units",
        "lu thi zat myan myan thin de",
    ],
    # ═══════════════════════════════════════
    # EAST ASIAN
    # ═══════════════════════════════════════
    "ja": [
        "タンク3の圧力を確認してください、高いです",
        "朝のシフト開始、全て正常",
        "昼前にガスケットを交換する必要があります",
        "ベイ2のトルクレンチを誰が持って行った？",
        "上司が今日中にレポートを欲しいと言っている",
        "今日の目標は500個",
        "新人の覚えが早い",
        "油温が高い、注意して",
        "休憩時間、お茶いる人？",
        "10時に安全ミーティング、忘れないで",
        "夜勤引き継ぎ：ポンプBから異音",
        "配送トラックがゲート3に到着",
        "品質がバッチ47を不合格にした、仕様を再確認して",
        "課長、お誕生日おめでとうございます",
        "週末の残業が承認された",
    ],
    "ko": [
        "탱크 3 압력 확인해주세요, 높습니다",
        "오전 근무 시작, 모두 정상",
        "점심 전에 가스켓 교체해야 합니다",
        "베이 2에서 토크 렌치 누가 가져갔어요?",
        "팀장님이 오늘 안에 보고서 달라고 했어요",
        "오늘 목표 500개",
        "신입이 빨리 배우고 있어요",
        "오일 온도 높아 보여요, 지켜봐 주세요",
        "쉬는 시간, 커피 마실 사람?",
        "10시에 안전 미팅, 잊지 마세요",
        "야간 인수인계: 펌프 B에서 소음 발생",
        "배송 트럭이 3번 게이트에 도착했어요",
    ],
    "zh": [
        "检查3号罐压力，偏高了",
        "早班开始了，一切正常",
        "午饭前得把垫片换了",
        "谁从2号区拿走了扭矩扳手？",
        "主管说今天下班前要交报告",
        "今天目标500件",
        "新来的学得挺快",
        "油温偏高，盯着点",
        "休息一下，谁要喝茶？",
        "十点安全会议，别忘了",
        "夜班交接：B泵有异响",
        "送货卡车到三号门了",
        "质量部把47批次退了，重新核对规格",
        "老板生日快乐，食堂有蛋糕",
        "周末加班批了",
    ],
    # ═══════════════════════════════════════
    # EUROPEAN
    # ═══════════════════════════════════════
    "de": [
        "Tank 3 Druck pruefen, ist zu hoch",
        "Fruehschicht beginnt, alles klar",
        "Dichtung muss vor Mittag gewechselt werden",
        "Wer hat den Drehmomentschluessel aus Bucht 2 genommen?",
        "Vorarbeiter will den Bericht bis Feierabend",
        "Tagesziel sind 500 Stueck",
        "Der Neue lernt schnell",
        "Oeltemperatur sieht hoch aus, Auge drauf",
        "Pause, jemand Kaffee?",
        "Sicherheitsbesprechung um 10, nicht vergessen",
        "Nachtschicht Uebergabe: Pumpe B macht Geraeusche",
        "Lieferwagen an Tor 3 angekommen",
    ],
    "fr": [
        "verifier la pression du reservoir 3, trop elevee",
        "equipe du matin commence, tout est bon",
        "faut changer le joint avant midi",
        "qui a pris la cle dynamometrique du poste 2?",
        "le chef veut le rapport avant la fin de journee",
        "objectif du jour: 500 pieces",
        "le nouveau apprend vite",
        "temperature huile trop haute, surveillez",
        "pause, quelqu'un veut un cafe?",
        "reunion securite a 10h, n'oubliez pas",
        "passation equipe nuit: pompe B fait du bruit",
        "camion livraison arrive porte 3",
    ],
    "pt": [
        "verifica a pressao do tanque 3, ta alta",
        "turno da manha comecou, tudo certo",
        "precisa trocar a junta antes do almoco",
        "quem pegou a chave de torque do box 2?",
        "supervisor quer o relatorio ate o fim do dia",
        "meta de hoje e 500 pecas",
        "o novato ta aprendendo rapido",
        "temperatura do oleo ta alta, fica de olho",
        "hora do intervalo, alguem quer cafe?",
        "reuniao de seguranca as 10, nao esquece",
        "passagem de turno noite: bomba B ta fazendo barulho",
        "caminhao de entrega chegou no portao 3",
    ],
    "es": [
        "revisa la presion del tanque 3, esta alta",
        "turno de manana empezando, todo bien",
        "hay que cambiar la junta antes del almuerzo",
        "quien se llevo la llave de torque del area 2?",
        "el supervisor quiere el reporte antes de salir",
        "meta de hoy 500 unidades",
        "el nuevo aprende rapido",
        "temperatura del aceite esta alta, ojo",
        "hora de descanso, alguien quiere cafe?",
        "reunion de seguridad a las 10, no se olviden",
        "relevo nocturno: la bomba B hace ruido",
        "llego el camion de entrega al porton 3",
    ],
    "it": [
        "controlla la pressione del serbatoio 3, e alta",
        "turno mattutino iniziato, tutto ok",
        "bisogna cambiare la guarnizione prima di pranzo",
        "chi ha preso la chiave dinamometrica dal box 2?",
        "il capo vuole il rapporto entro fine giornata",
        "obiettivo di oggi 500 pezzi",
        "il nuovo impara veloce",
        "temperatura olio troppo alta, tenetela d'occhio",
        "pausa, qualcuno vuole un caffe?",
        "riunione sicurezza alle 10, non dimenticate",
    ],
    "pl": [
        "sprawdz cisnienie zbiornika 3, za wysokie",
        "zmiana poranna zaczela sie, wszystko ok",
        "trzeba wymienic uszczelke przed obiadem",
        "kto wzial klucz dynamometryczny z boksu 2?",
        "kierownik chce raport do konca dnia",
        "dzisiejszy cel to 500 sztuk",
        "nowy szybko sie uczy",
        "temperatura oleju wysoka, obserwujcie",
        "przerwa, ktos chce kawe?",
        "spotkanie BHP o 10, nie zapomnijcie",
    ],
    "ru": [
        "prover davleniye v bake 3, vysokoye",
        "utrennaya smena nachalas, vsyo v norme",
        "nado zamenit prokladku do obeda",
        "kto vzyal dinamometricheskiy klyuch iz zony 2?",
        "nachalnik khochet otchyot do kontsa dnya",
        "segodnya tsel 500 shtuk",
        "novichok bystro uchitsya",
        "temperatura masla vysokaya, sledite",
        "pereryv, kto khochet chay?",
        "soveshchaniye po bezopasnosti v 10, ne zabudtye",
    ],
    "ro": [
        "verifica presiunea la rezervor 3, e prea mare",
        "schimbul de dimineata a inceput, totul ok",
        "trebuie schimbata garnitura inainte de masa",
        "cine a luat cheia dinamometrica din zona 2?",
        "seful vrea raportul pana la sfarsitul zilei",
        "tinta de azi e 500 bucati",
        "noul angajat invata repede",
        "temperatura uleiului e mare, urmariti",
        "pauza, vrea cineva o cafea?",
        "sedinta SSM la 10, nu uitati",
    ],
    "nl": [
        "check de druk van tank 3, te hoog",
        "ochtendploeg begint, alles is goed",
        "pakking moet voor de lunch vervangen worden",
        "wie heeft de momentsleutel uit vak 2 gepakt?",
        "voorman wil het rapport voor einde dag",
        "doel vandaag is 500 stuks",
        "de nieuwe leert snel",
        "olietemperatuur lijkt hoog, hou in de gaten",
        "pauze, iemand koffie?",
        "veiligheidsvergadering om 10, niet vergeten",
    ],
    # ═══════════════════════════════════════
    # AFRICAN
    # ═══════════════════════════════════════
    "sw": [
        "angalia shinikizo la tank 3, ni juu sana",
        "zamu ya asubuhi imeanza, kila kitu sawa",
        "lazima tubadilishe gasket kabla ya chakula",
        "nani amechukua spana kutoka bay 2?",
        "msimamizi anataka ripoti leo kabla ya kurudi",
        "lengo la leo ni vipande 500",
        "mtu mpya anajifunza haraka",
        "joto la mafuta ni juu, angalia",
        "mapumziko, mtu yeyote anataka chai?",
        "mkutano wa usalama saa 4, usisahau",
    ],
    "ha": [
        "duba matsin lamba na tank 3, ya yi yawa",
        "shift na safiya ya fara, komai lafiya",
        "dole a canja gasket kafin abincin rana",
        "wane ya dauki torque wrench daga bay 2?",
        "supervisor yana so rahoton yau",
        "manufa ta yau 500 ne",
        "sabon mutumin yana koyo da sauri",
        "zafin mai ya yi yawa, ku kula",
        "lokacin hutu, wani yana son shayi?",
        "taron tsaro da karfe 10, kada ku manta",
    ],
    "am": [
        "tank 3 pressure check aderg, kefi new",
        "yesequat shift jemere, hulunem tefetro new",
        "misa belu gasket mechawed yasfelegual",
        "bay 2 lay torque wrench man wesedeW?",
        "supervisor report zare yifelgal alew",
        "yezare gibye 500 units new",
        "addisu sewye betam befikad yimaral",
        "yezeyit mewekeat kefi new, tikuret",
    ],
    "yo": [
        "sewo pressure ti tank 3, o ga ju",
        "shift owuro ti bere, ohun gbogbo dara",
        "a nilo lati yi gasket pada ki o to onje osan",
        "tani mu torque wrench lati bay 2?",
        "supervisor fe iroyin loni",
        "afojusun oni ni awon ege 500",
        "omo titun n koya ni kiakia",
        "iwon ooru epo ga, e maa wo o",
    ],
    # ═══════════════════════════════════════
    # CENTRAL ASIAN
    # ═══════════════════════════════════════
    "kk": [
        "tank 3 qysymyn tekseriñiz, joğary",
        "tañğy auysym bastaldy, bäri durys",
        "tüskı asqa deyin prokladka auystiru kerek",
        "bay 2 den torque achqyshyn kim aldy?",
        "basshı esepti bugın kerek dedi",
        "bugıngi maqsat 500 birlık",
    ],
    "uz": [
        "tank 3 bosimini tekshiring, baland",
        "ertalab smena boshlandi, hammasi yaxshi",
        "tushlikdan oldin prokladka almashtiramiz",
        "bay 2 dan moment kalitini kim oldi?",
        "rahbar hisobotni bugun so'radi",
        "bugungi maqsad 500 dona",
    ],
}

# Total languages
TOTAL_LANGUAGES = len(WORKPLACE_PHRASES)
