"""Unknown Unknowns — teach AI to recognize when the real answer isn't among the obvious options.

Most AI training assumes the correct answer is always among the options.
This module generates scenarios where:
1. The correct answer is NONE of the obvious choices
2. The real cause is something nobody considered
3. The right action is to say 'I don't know' or 'need more data'
"""
import random
from typing import Dict, List

WORLD_UNKNOWNS: Dict[str, List[Dict]] = {
    'healthcare': [
        {'observable_symptoms': ['fever', 'cough', 'fatigue'], 'obvious_suspects': ['flu', 'COVID', 'pneumonia'], 'actual_cause': 'carbon monoxide poisoning from faulty heater', 'why_missed': 'environmental cause not in standard differential', 'lesson': 'always consider non-medical causes for medical symptoms', 'correct_response': 'Ask about home environment before concluding respiratory infection'},
        {'observable_symptoms': ['patient_deteriorating', 'treatment_not_working', 'worsening_labs'], 'obvious_suspects': ['drug_resistance', 'wrong_diagnosis', 'non_compliance'], 'actual_cause': 'herbal supplement (St Johns Wort) inducing CYP3A4 and neutralizing medication', 'why_missed': 'patients dont consider supplements as real medicine and dont report them', 'lesson': 'always ask about supplements, OTC meds, and dietary changes explicitly', 'correct_response': 'Perform comprehensive medication reconciliation including all supplements and OTC products'},
        {'observable_symptoms': ['recurring_falls', 'confusion', 'weakness', 'elderly_patient'], 'obvious_suspects': ['dementia', 'stroke', 'inner_ear_disorder', 'medication_side_effect'], 'actual_cause': 'loose carpet edge in hallway at home causing trips, not neurological at all', 'why_missed': 'clinicians focused on medical causes without home safety assessment', 'lesson': 'not every symptom cluster has a medical cause — environmental factors matter', 'correct_response': 'Order home safety assessment before additional neurological testing'},
        {'observable_symptoms': ['HbA1c_rising', 'claims_compliance', 'insulin_doses_correct'], 'obvious_suspects': ['patient_lying_about_diet', 'insulin_resistance_worsening', 'wrong_insulin_type'], 'actual_cause': 'patient storing insulin next to freezer vent — cold damage destroying efficacy', 'why_missed': 'storage conditions rarely verified; patient genuinely compliant with injection schedule', 'lesson': 'medication storage and handling can silently destroy drug efficacy', 'correct_response': 'Verify insulin storage conditions and check vial appearance before assuming non-compliance'},
        {'observable_symptoms': ['cluster_of_headaches', 'same_office_floor', 'afternoon_onset'], 'obvious_suspects': ['stress', 'screen_fatigue', 'poor_ergonomics', 'viral_illness'], 'actual_cause': 'new carpet adhesive off-gassing VOCs that accumulate by afternoon in poorly ventilated area', 'why_missed': 'occupational health not consulted; individual cases treated in isolation without noticing cluster', 'lesson': 'workplace symptom clusters often have building/environmental causes', 'correct_response': 'Map cases geographically and temporally — if clustered, investigate building environment not individual health'},
        {'observable_symptoms': ['chronic_fatigue', 'weight_gain', 'depression', 'normal_thyroid'], 'obvious_suspects': ['hypothyroidism', 'depression', 'sleep_apnea', 'diabetes'], 'actual_cause': 'mold exposure from hidden water damage behind bedroom wall', 'why_missed': 'standard labs normal; no one asked about home environment or recent water damage', 'lesson': 'when standard workup is negative, expand to environmental exposures', 'correct_response': 'Explore environmental factors — water damage, mold, new construction, chemical exposures at home'},
        {'observable_symptoms': ['pediatric_behavioral_changes', 'aggression', 'sleep_disruption'], 'obvious_suspects': ['ADHD', 'autism_spectrum', 'learning_disability', 'family_stress'], 'actual_cause': 'child being cyberbullied via gaming platform at night — parents unaware', 'why_missed': 'clinicians focused on neurodevelopmental diagnoses without exploring digital life', 'lesson': 'behavioral changes in children often have social/environmental triggers including online', 'correct_response': 'Explore full social environment including online activity before pursuing neurodevelopmental evaluation'},
        {'observable_symptoms': ['chest_pain', 'shortness_of_breath', 'young_patient', 'anxiety'], 'obvious_suspects': ['panic_attack', 'costochondritis', 'acid_reflux', 'anxiety_disorder'], 'actual_cause': 'five energy drinks per day causing caffeine-induced cardiac arrhythmia', 'why_missed': 'young patient assumed healthy; dietary caffeine intake never quantified', 'lesson': 'take thorough dietary and substance history even in young healthy patients', 'correct_response': 'Quantify caffeine and stimulant intake, get ECG, complete dietary history before attributing to anxiety'},
        {'observable_symptoms': ['post_surgical_pain_not_resolving', 'normal_imaging', 'no_infection'], 'obvious_suspects': ['nerve_damage', 'psychosomatic', 'drug_seeking', 'surgical_complication'], 'actual_cause': 'retained surgical sponge not visible on X-ray due to degraded radiopaque marker', 'why_missed': 'X-ray clear and sponge count documented as correct (counting error)', 'lesson': 'normal imaging doesnt exclude all physical causes — consider imaging modality limitations', 'correct_response': 'Order CT scan even with negative X-ray; independently verify sponge count documentation'},
        {'observable_symptoms': ['intermittent_hypotension', 'dizziness', 'only_at_work'], 'obvious_suspects': ['orthostatic_hypotension', 'cardiac_arrhythmia', 'vasovagal', 'dehydration'], 'actual_cause': 'office chair hydraulic leak releasing trace chemicals; symptoms resolve on weekends', 'why_missed': 'temporal pattern attributed to work stress rather than physical environment', 'lesson': 'when symptoms have temporal pattern, consider ALL factors that differ between periods', 'correct_response': 'Investigate what is physically different about work environment rather than assuming stress'},
    ],
    'finance': [
        {'observable_symptoms': ['stock_dropping_5_percent', 'no_news', 'high_volume'], 'obvious_suspects': ['insider_selling', 'sector_rotation', 'earnings_miss_coming'], 'actual_cause': 'large pension fund mechanically rebalancing quarterly — purely algorithmic, no fundamental reason', 'why_missed': 'rebalancing flows not reported in real-time; assumed information-driven selling', 'lesson': 'not all price moves are information-driven — mechanical flows move markets without meaning', 'correct_response': 'Check if quarter-end, any index reconstitution, or ETF rebalancing before assuming negative information'},
        {'observable_symptoms': ['model_predictions_off', 'started_this_quarter', 'no_code_changes'], 'obvious_suspects': ['market_regime_change', 'data_quality_issue', 'overfitting', 'parameter_drift'], 'actual_cause': 'daylight saving time change caused timezone bug in data feed — 3 days shifted by 1 hour', 'why_missed': 'DST bugs are subtle; data looks normal on spot checks; affects only time-sensitive features', 'lesson': 'always check around DST transitions, year boundaries, and leap seconds for time bugs', 'correct_response': 'Check data infrastructure around degradation start date — DST transition, feed provider update, clock sync'},
        {'observable_symptoms': ['unusual_trading_before_announcements', 'specific_client', 'consistent_alpha'], 'obvious_suspects': ['insider_trading', 'front_running', 'information_leakage'], 'actual_cause': 'client uses satellite imagery of parking lots and construction sites — legitimate alternative data', 'why_missed': 'pattern looks exactly like insider trading but is legal alternative data edge', 'lesson': 'not all edge is illegal — alternative data can produce seemingly prescient legal trades', 'correct_response': 'Investigate clients stated strategy before escalating; alternative data produces legal but suspicious-looking patterns'},
        {'observable_symptoms': ['settlement_failures_increasing', 'specific_counterparty', 'intermittent'], 'obvious_suspects': ['counterparty_distress', 'operational_issues', 'liquidity_problems'], 'actual_cause': 'counterparty upgraded settlement system with different message format that truncates long reference numbers', 'why_missed': 'failures are intermittent (only when ref numbers exceed 16 chars); their tests pass', 'lesson': 'intermittent failures between systems often stem from edge cases in message format', 'correct_response': 'Compare failing vs successful trades — look for differences in field lengths, special characters, instrument types'},
        {'observable_symptoms': ['PnL_attribution_mismatch', 'small_but_persistent', 'theoretical_vs_actual'], 'obvious_suspects': ['pricing_model_error', 'transaction_cost_underestimate', 'execution_slippage'], 'actual_cause': 'firms clock is 3 seconds ahead of exchange clock causing systematic mark-to-market at wrong prices', 'why_missed': '3-second drift within NTP tolerance; tiny per-trade impact accumulates; standard reconciliation doesnt check timestamps', 'lesson': 'persistent small errors often have infrastructure root causes — check clocks, rounding, encoding', 'correct_response': 'Check clock synchronization, timestamp handling, rounding conventions, and FX rate snapshot timing'},
        {'observable_symptoms': ['volatility_smile_distorted', 'specific_expiry', 'no_macro_event'], 'obvious_suspects': ['large_positioning', 'earnings_event', 'market_maker_inventory'], 'actual_cause': 'options market makers hedging algorithm has bug at that strike/expiry creating artificial supply/demand', 'why_missed': 'microstructure issues look identical to information-driven flows without seeing MM book', 'lesson': 'market microstructure effects can masquerade as fundamental information', 'correct_response': 'Isolated anomaly at specific strike/expiry may be microstructure not information — check if it persists or self-corrects'},
        {'observable_symptoms': ['regulatory_test_orders_in_production', 'strange_fills', 'compliance_alert'], 'obvious_suspects': ['rogue_trader', 'unauthorized_access', 'system_breach'], 'actual_cause': 'regulator running scheduled conformance tests but didnt notify ops team — legitimate test orders mistaken for real trades', 'why_missed': 'test notification went to compliance inbox not ops; orders look real in monitoring', 'lesson': 'regulatory test programs generate real-looking traffic — ensure all teams know test schedules', 'correct_response': 'Before escalating as incident, check with compliance if any regulatory testing scheduled for today'},
        {'observable_symptoms': ['client_withdrawals_increasing', 'performance_good', 'no_complaints'], 'obvious_suspects': ['competitor_offering_better', 'market_timing', 'fee_sensitivity'], 'actual_cause': 'mobile app redesign made withdrawal button prominent while reinvest button was buried in menu', 'why_missed': 'UX changes not communicated to fund management; behavioral correlation with app update not analyzed', 'lesson': 'customer behavior changes often have UX/channel explanations rather than fundamental product issues', 'correct_response': 'Check for recent changes to client touchpoints — app updates, statement redesigns, new self-service features'},
        {'observable_symptoms': ['bond_yields_diverging', 'same_issuer', 'same_maturity'], 'obvious_suspects': ['credit_risk_change', 'liquidity_premium', 'rating_change_coming'], 'actual_cause': 'one bond accidentally excluded from major index — affects which funds must hold it', 'why_missed': 'index inclusion is data management detail traders dont monitor', 'lesson': 'price differences between identical securities often have technical/structural explanations', 'correct_response': 'Check if both bonds are in same indices — recent index reconstitution may have dropped one'},
    ],
    'coding': [
        {'observable_symptoms': ['production_errors_spike_every_tuesday', '2am_timeframe', 'server_briefly_unreachable'], 'obvious_suspects': ['cron_job_conflict', 'deployment_issue', 'load_spike', 'batch_process'], 'actual_cause': 'cleaning crew unplugs server rack to plug in vacuum cleaner every Tuesday at 2am', 'why_missed': 'ops team never communicates with facilities; power loss logged but assumed UPS testing', 'lesson': 'physical infrastructure affects software — talk to facilities and maintenance teams', 'correct_response': 'Recurring pattern at exact same time suggests physical/environmental cause — check what happens in server room at that time'},
        {'observable_symptoms': ['api_latency_increased_3x', 'gradual_degradation', 'no_code_changes'], 'obvious_suspects': ['database_slow', 'memory_leak', 'network_congestion', 'increased_traffic'], 'actual_cause': 'SSL certificate expiring in 7 days — client libraries doing extra verification and retry storms', 'why_missed': 'cert still valid so no errors; overhead is subtle; client retries not visible server-side', 'lesson': 'upcoming expirations cause issues BEFORE actual expiry — certs, tokens, licenses', 'correct_response': 'Check certificate expiry dates, DNS TTLs, credential rotations due, and license expirations'},
        {'observable_symptoms': ['DNS_resolution_returning_wrong_IP', 'intermittent', 'some_users_affected'], 'obvious_suspects': ['DNS_poisoning_attack', 'misconfigured_record', 'propagation_delay'], 'actual_cause': 'DNS TTL was set to 48 hours — old cached wrong answer persists at recursive resolvers long after fix applied', 'why_missed': 'record looks correct in authoritative DNS; issue is stale caches at ISP resolvers still serving old record', 'lesson': 'DNS TTL means the WRONG answer persists that long too — high TTLs are dangerous during incidents', 'correct_response': 'Check TTL on the record and calculate when all caches will expire — cannot force ISP resolvers to flush'},
        {'observable_symptoms': ['scheduled_jobs_running_twice', 'started_last_weekend', 'spring_only'], 'obvious_suspects': ['cron_misconfiguration', 'cluster_failover', 'duplicate_deployment', 'race_condition'], 'actual_cause': 'daylight saving time spring-forward created duplicate execution — scheduler using wall clock time saw 2am twice', 'why_missed': 'DST bugs only manifest twice per year; scheduler uses local time not UTC; tests never run at DST boundary', 'lesson': 'use UTC for all scheduled operations — wall clock time is not monotonic during DST transitions', 'correct_response': 'Check if scheduler uses local time vs UTC — DST transitions create duplicate or skipped hours'},
        {'observable_symptoms': ['tests_pass_locally_fail_CI', 'non_deterministic', 'flaky'], 'obvious_suspects': ['race_condition', 'test_isolation', 'environment_difference', 'timezone'], 'actual_cause': 'CI machines have faster SSDs — test assertions assume filesystem returns files in write-order but SSD doesnt guarantee this', 'why_missed': 'local spinning disk returns consistent order by accident; SSD in CI has different ordering', 'lesson': 'never assume ordering unless explicitly specified — filesystems, hashmaps, queries without ORDER BY', 'correct_response': 'Check for implicit ordering assumptions — file listing, map iteration, query results without explicit sort'},
        {'observable_symptoms': ['memory_usage_growing', 'no_obvious_leak', 'profiler_shows_nothing'], 'obvious_suspects': ['memory_leak', 'cache_not_evicting', 'connection_pool_growing'], 'actual_cause': 'Linux kernel transparent huge pages (THP) causing memory fragmentation — app memory stable but THP overhead grows', 'why_missed': 'app-level profiling doesnt show kernel memory overhead; THP invisible to user-space tools', 'lesson': 'not all resource issues are in your application — OS, runtime, and hardware contribute invisible overhead', 'correct_response': 'If app profiling shows no leak, check OS level — transparent huge pages, kernel slab cache, memory fragmentation'},
        {'observable_symptoms': ['deployment_succeeds_but_app_broken', 'rollback_fixes_it', 'code_diff_looks_fine'], 'obvious_suspects': ['config_mismatch', 'dependency_change', 'build_corruption', 'feature_flag'], 'actual_cause': 'new .env.example file picked up by Dockers broad COPY command, overriding actual environment variables', 'why_missed': '.env.example added for documentation; COPY . is overly broad; nobody noticed it in container image', 'lesson': 'broad file copies in build systems are dangerous — use .dockerignore and explicit COPY targets', 'correct_response': 'Diff actual container contents between working and broken versions, not just source code'},
        {'observable_symptoms': ['websocket_connections_dropping', 'mobile_users_only', 'afternoon_hours'], 'obvious_suspects': ['mobile_app_bug', 'timeout_config', 'server_connection_limits', 'keepalive_interval'], 'actual_cause': 'cellular carriers NAT tables expire idle connections after 30s during peak hours to reclaim resources', 'why_missed': 'works fine on WiFi; carrier NAT behavior invisible to developers and varies by carrier/time', 'lesson': 'mobile network differs from WiFi — NAT timeouts, connection reuse, traffic shaping all affect apps', 'correct_response': 'Check WebSocket heartbeat interval — carrier NAT can expire idle connections in 30 seconds during peak'},
        {'observable_symptoms': ['search_relevance_degraded', 'no_algorithm_changes', 'no_index_changes'], 'obvious_suspects': ['data_quality', 'index_corruption', 'query_parser_bug', 'algorithm_regression'], 'actual_cause': 'competitor launched SEO spam campaign that polluted training data for weekly relevance model retrain', 'why_missed': 'automated retraining doesnt validate that training data distribution hasnt shifted', 'lesson': 'automated ML pipelines need data validation gates — training data can be poisoned externally', 'correct_response': 'Compare training data distributions between this retrain and previous — look for anomalous content or volume spikes'},
        {'observable_symptoms': ['cpu_100_percent', 'single_core', 'specific_time_window'], 'obvious_suspects': ['infinite_loop', 'regex_backtracking', 'crypto_mining_malware', 'runaway_process'], 'actual_cause': 'log rotation tool compressing 50GB log file on same server — legitimate operation, poor scheduling', 'why_missed': 'log rotation is infrastructure developers dont think about; legitimate process so monitoring doesnt alert', 'lesson': 'background system processes compete with your application — log rotation, backups, antivirus scans', 'correct_response': 'Check what system processes run at that time: log rotation, backups, antivirus scans, apt updates'},
    ],
    'energy': [
        {'observable_symptoms': ['generator_efficiency_dropping', 'gradual_decline', 'spring_season'], 'obvious_suspects': ['fuel_quality', 'aging_equipment', 'maintenance_overdue', 'fouled_heat_exchanger'], 'actual_cause': 'bird nests blocking cooling air intake — seasonal, happens every spring', 'why_missed': 'monitoring focuses on internal metrics; external physical obstructions not instrumented', 'lesson': 'seasonal performance patterns often have biological/environmental causes — check wildlife interaction', 'correct_response': 'Inspect external air intakes, cooling towers, and vents for bird nests, pollen, vegetation growth'},
        {'observable_symptoms': ['substation_tripping_intermittent', 'no_overload', 'rural_area'], 'obvious_suspects': ['insulator_flashover', 'protection_relay_fault', 'cable_degradation', 'weather_related'], 'actual_cause': 'squirrel chewing through cable insulation causing intermittent ground faults', 'why_missed': 'damage only visible on close inspection; squirrel activity sporadic; insulation tests pass when dry', 'lesson': 'wildlife damage is a leading cause of unexplained outages in rural substations', 'correct_response': 'Physically inspect all exposed cables for animal damage — teeth marks, nesting material, droppings nearby'},
        {'observable_symptoms': ['plant_setpoints_drifting', 'no_operator_changes', 'subtle_shift'], 'obvious_suspects': ['instrument_calibration_drift', 'control_valve_stiction', 'process_condition_change'], 'actual_cause': 'routine software update to DCS changed default PID tuning parameters without operator notification', 'why_missed': 'update release notes buried parameter change in appendix; operators not informed; change is small but accumulates', 'lesson': 'software updates can silently change operational parameters — review ALL changes in control system updates', 'correct_response': 'Compare current setpoints and PID parameters against pre-update baseline — check DCS update release notes thoroughly'},
        {'observable_symptoms': ['solar_output_below_forecast', 'clear_sky', 'panels_appear_clean'], 'obvious_suspects': ['inverter_issue', 'panel_degradation', 'shading', 'forecast_error'], 'actual_cause': 'new building 2km away creates reflected glare that overheats one string of panels', 'why_missed': 'thermal imaging not done midday; reflected glare from distant buildings not in shading analysis', 'lesson': 'solar depends on entire surrounding environment — new construction miles away can affect output', 'correct_response': 'Check panel temperatures by string; investigate new construction or reflective surfaces that could cause localized heating'},
        {'observable_symptoms': ['transformer_humming_louder', 'no_overload', 'temperature_normal'], 'obvious_suspects': ['core_magnetostriction', 'loose_laminations', 'harmonic_distortion'], 'actual_cause': 'nearby data center installed new UPS injecting DC offset into grid causing transformer core saturation', 'why_missed': 'DC offset not measured by standard power quality monitors; source is different customers equipment', 'lesson': 'grid-connected equipment interactions are invisible without specific monitoring', 'correct_response': 'Check power quality for DC component and harmonics — any new large loads on same feeder recently?'},
        {'observable_symptoms': ['wind_turbine_yaw_errors', 'specific_turbines', 'intermittent'], 'obvious_suspects': ['yaw_motor_failure', 'wind_vane_calibration', 'software_bug', 'bearing_wear'], 'actual_cause': 'lightning strike 3 weeks ago magnetized nacelle structure, biasing compass-based yaw sensor', 'why_missed': 'lightning didnt cause immediate damage; residual magnetization not in troubleshooting guides', 'lesson': 'lightning effects can be delayed and subtle — residual magnetization affects sensors without obvious damage', 'correct_response': 'Check for recent lightning strikes; compass sensors can be affected by magnetization of nearby metal structures'},
        {'observable_symptoms': ['smart_meter_readings_inconsistent', 'billing_complaints', 'random_customers'], 'obvious_suspects': ['meter_hardware_failure', 'firmware_bug', 'communication_errors', 'tampering'], 'actual_cause': 'new 5G tower causing mesh network interference — meter communication packets getting corrupted', 'why_missed': '5G not in meters tested frequency environment; correlation with tower activation not checked', 'lesson': 'RF environment changes can affect IoT networks — new transmitters cause subtle data corruption', 'correct_response': 'Check for new RF sources in affected areas — cell towers, industrial equipment, other IoT deployments'},
        {'observable_symptoms': ['SCADA_phantom_readings', 'values_spike_then_normalize', 'correlates_with_weather'], 'obvious_suspects': ['sensor_failure', 'software_bug', 'cybersecurity_intrusion', 'EMI'], 'actual_cause': 'rainwater pooling in cable conduit creates intermittent ground loops during storms', 'why_missed': 'grounding issues notoriously hard to diagnose remotely; correlation with rain not obvious in logs', 'lesson': 'intermittent instrumentation issues that correlate with weather often have grounding or moisture root cause', 'correct_response': 'Check correlation with weather/rain — ground loops from moisture in cable trays cause spurious readings'},
        {'observable_symptoms': ['battery_storage_capacity_declining_fast', 'temperature_controlled', 'exceeds_warranty_curve'], 'obvious_suspects': ['cell_defect', 'BMS_calibration', 'thermal_issue', 'manufacturing_defect'], 'actual_cause': 'building vibration from adjacent highway construction causing micro-fractures in electrode material', 'why_missed': 'vibration monitoring only checks earthquakes; sustained low-frequency vibration from construction not captured', 'lesson': 'batteries are sensitive to sustained vibration — check nearby construction or heavy traffic', 'correct_response': 'Check for sustained vibration sources: nearby construction, heavy vehicles, industrial equipment'},
    ],
    'robotics': [
        {'observable_symptoms': ['robot_arm_position_drift', 'gradual', 'temperature_dependent'], 'obvious_suspects': ['encoder_failure', 'motor_degradation', 'calibration_drift', 'gear_backlash'], 'actual_cause': 'thermal expansion of mounting bolts in afternoon sun through skylight shifts base plate by 0.2mm', 'why_missed': 'robot specs assume stable mounting; skylight solar gain not in thermal model; drift reverses overnight', 'lesson': 'precision machinery is affected by thermal environment in ways not covered by equipment specs', 'correct_response': 'Check for thermal sources affecting mounting structure — skylights, nearby furnaces, seasonal sun angle changes'},
        {'observable_symptoms': ['pick_and_place_failure_rate_up', 'specific_parts_only', 'vision_system_fine'], 'obvious_suspects': ['gripper_wear', 'vision_calibration', 'part_tolerance_change', 'conveyor_speed'], 'actual_cause': 'supplier changed plastic resin in parts — same dimensions but different surface friction coefficient', 'why_missed': 'parts pass dimensional QC; surface properties not in incoming inspection; supplier didnt notify of material change', 'lesson': 'material property changes are invisible to dimensional inspection — friction, flexibility, static charge all matter', 'correct_response': 'Check if supplier changed materials recently; test surface friction and static properties, not just dimensions'},
        {'observable_symptoms': ['AGV_navigation_errors', 'specific_zone', 'time_of_day_dependent'], 'obvious_suspects': ['lidar_degradation', 'map_outdated', 'floor_reflectance', 'wheel_slippage'], 'actual_cause': 'afternoon sun through loading dock door creates lidar-blinding glare on polished floor in that zone', 'why_missed': 'commissioning done in winter with door closed; summer sun angle creates specular reflection', 'lesson': 'optical navigation systems are affected by lighting conditions that change seasonally', 'correct_response': 'Check lighting conditions at failure time — sun position, reflective surfaces, door positions all affect lidar'},
        {'observable_symptoms': ['collaborative_robot_emergency_stops', 'no_contact_detected', 'random'], 'obvious_suspects': ['safety_sensor_fault', 'EMI_interference', 'software_bug', 'vibration_triggering_force_sensor'], 'actual_cause': 'nearby welding robot creating EMI spikes that trigger force/torque sensor false readings', 'why_missed': 'robots installed at different times; EMI survey done before welding cell added; interference is sporadic', 'lesson': 'electromagnetic compatibility between robots must be tested as a system, not individually', 'correct_response': 'Correlate e-stops with activity of nearby equipment — welding, induction heating, VFDs can cause EMI'},
        {'observable_symptoms': ['warehouse_robot_fleet_efficiency_declining', 'gradual', 'all_robots'], 'obvious_suspects': ['path_planning_degradation', 'battery_aging', 'software_update_regression', 'increased_order_complexity'], 'actual_cause': 'warehouse racking slightly shifted after forklift impact — map is now 3cm off reality causing replanning loops', 'why_missed': 'shift too small for humans to notice; robots compensate by replanning rather than failing; no single error to alert on', 'lesson': 'robot fleet gradual degradation often means their world model diverged from reality incrementally', 'correct_response': 'Resurvey physical environment and compare against robots internal map — small shifts accumulate into big inefficiency'},
        {'observable_symptoms': ['inspection_robot_missing_defects', 'false_negatives_increasing', 'camera_appears_fine'], 'obvious_suspects': ['camera_lens_dirty', 'lighting_change', 'model_drift', 'focus_calibration'], 'actual_cause': 'cleaning crew using new glass cleaner on inspection window leaves invisible residue that scatters UV inspection light', 'why_missed': 'window looks perfectly clean to human eye; UV light scattering invisible; residue builds up over cleanings', 'lesson': 'optical inspection is affected by every surface between camera and target — cleaning products matter', 'correct_response': 'Clean inspection optics with approved solvent only; check if cleaning products changed recently'},
        {'observable_symptoms': ['drone_battery_life_shorter_than_spec', 'new_units', 'meets_spec_in_lab'], 'obvious_suspects': ['battery_defect', 'payload_overweight', 'firmware_power_management', 'motor_efficiency'], 'actual_cause': 'operating altitude is 2000m above sea level — thinner air requires higher RPM for same lift, consuming more power', 'why_missed': 'specs tested at sea level; altitude effect on power consumption not in datasheet; buyer didnt consider operating altitude', 'lesson': 'robotics performance specs assume standard conditions — altitude, temperature, humidity all affect real-world performance', 'correct_response': 'Check operating altitude vs test conditions — air density affects propulsion efficiency significantly above 1500m'},
        {'observable_symptoms': ['robot_welding_quality_degraded', 'specific_shift', 'same_program'], 'obvious_suspects': ['wire_feed_issue', 'gas_flow_rate', 'operator_error', 'fixture_wear'], 'actual_cause': 'night shift HVAC creates air current across weld cell that disrupts shielding gas coverage', 'why_missed': 'air current too gentle to feel; HVAC mode changes between shifts; day shift weld quality is fine', 'lesson': 'welding and coating processes are extremely sensitive to air movement invisible to humans', 'correct_response': 'Check for air currents in weld cell during affected shift — HVAC, doors, fans can disrupt gas shielding'},
        {'observable_symptoms': ['surgical_robot_calibration_failing', 'morning_only', 'passes_later'], 'obvious_suspects': ['thermal_warmup_needed', 'encoder_cold_start_issue', 'software_initialization_bug'], 'actual_cause': 'building settles overnight and OR floor shifts 0.05mm — returns to position as building warms and expands', 'why_missed': 'structural movement below measurement threshold of standard instruments; OR floor assumed perfectly rigid', 'lesson': 'buildings are not rigid — thermal expansion, settling, and wind loading create micro-movements that affect precision systems', 'correct_response': 'Monitor floor-level reference against external datum — building thermal effects can shift precision equipment overnight'},
    ],
    'agriculture': [
        {'observable_symptoms': ['crop_yield_declining_one_field', 'soil_tests_normal', 'same_seed_variety'], 'obvious_suspects': ['soil_depletion', 'pest_damage', 'irrigation_problem', 'seed_quality'], 'actual_cause': 'nearby highway construction changed water table drainage pattern — field now waterlogged at root depth', 'why_missed': 'surface appears normal; water table change from distant construction not connected; root zone saturation not in standard soil test', 'lesson': 'off-site construction can change hydrology affecting fields hundreds of meters away', 'correct_response': 'Check water table depth and drainage patterns — any nearby construction, grading, or land use changes affecting hydrology?'},
        {'observable_symptoms': ['GPS_guided_equipment_drifting', 'specific_field', 'consistent_offset'], 'obvious_suspects': ['GPS_receiver_issue', 'base_station_error', 'satellite_geometry', 'multipath'], 'actual_cause': 'new cell tower 500m away causing RF interference with GPS correction signal (RTK)', 'why_missed': 'cell tower frequency technically non-overlapping but intermodulation products fall in GPS band; GPS shows fix but with degraded accuracy', 'lesson': 'new RF infrastructure near fields can degrade precision GPS without causing obvious signal loss', 'correct_response': 'Check for new RF sources near the field — cell towers can interfere with RTK correction signals through intermodulation'},
        {'observable_symptoms': ['automated_irrigation_overwatering', 'soil_moisture_sensors_show_dry', 'visual_inspection_shows_wet'], 'obvious_suspects': ['sensor_calibration', 'soil_type_change', 'sensor_placement_wrong', 'controller_bug'], 'actual_cause': 'soil moisture sensors installed in sandy lens while surrounding soil is clay — sensor reads dry because sand drains fast even though field is saturated', 'why_missed': 'sensors installed correctly per procedure but local soil heterogeneity not mapped; single point measurement not representative', 'lesson': 'point measurements in heterogeneous fields can be wildly unrepresentative — multiple sensors or soil mapping needed', 'correct_response': 'Verify sensor location soil type matches field average — dig near sensor to check if local conditions differ from surroundings'},
        {'observable_symptoms': ['livestock_behavioral_changes', 'reduced_feeding', 'no_illness_detected'], 'obvious_suspects': ['disease_onset', 'feed_quality', 'weather_stress', 'social_hierarchy_disruption'], 'actual_cause': 'new ultrasonic pest deterrent on neighboring property emitting frequencies cattle can hear but humans cannot', 'why_missed': 'ultrasonic devices inaudible to farmers; neighboring propertys pest control not communicated; cattle stress attributed to weather', 'lesson': 'animals sense stimuli invisible to humans — ultrasound, EMF, vibration from off-site sources affect behavior', 'correct_response': 'Check for new equipment on neighboring properties — ultrasonic devices, generators, or industrial activity animals can detect'},
        {'observable_symptoms': ['fungal_disease_outbreak', 'unexpected_timing', 'resistant_variety'], 'obvious_suspects': ['new_pathogen_strain', 'resistance_breakdown', 'microclimate_issue', 'spray_timing_missed'], 'actual_cause': 'solar farm installed upwind creates microclimate — panels trap morning dew creating humidity pocket that favors fungal growth', 'why_missed': 'solar farm 1km away; microclimate effects not modeled; humidity monitoring at weather station doesnt capture localized effect', 'lesson': 'large installations change local microclimates in unexpected ways — wind patterns, humidity, temperature', 'correct_response': 'Survey upwind land use changes — solar farms, buildings, tree removal all alter microclimate patterns that affect disease pressure'},
        {'observable_symptoms': ['harvest_quality_variable', 'same_field', 'random_patches'], 'obvious_suspects': ['soil_variability', 'irrigation_uniformity', 'pest_pockets', 'seed_lot_variation'], 'actual_cause': 'historical landfill beneath field (pre-regulation, unmarked) creating variable soil chemistry in patches', 'why_missed': 'landfill predates current ownership; not on any modern survey; soil tests average out localized contamination', 'lesson': 'historical land use creates invisible legacies — always research full site history for unexplained variability', 'correct_response': 'Research complete land use history including pre-regulation era; conduct targeted deep soil sampling in affected patches'},
        {'observable_symptoms': ['drone_crop_monitoring_giving_false_readings', 'NDVI_inconsistent', 'ground_truth_contradicts'], 'obvious_suspects': ['camera_calibration', 'flight_altitude_variation', 'atmospheric_haze', 'time_of_day_sun_angle'], 'actual_cause': 'wildfire smoke 200km away creating uneven atmospheric haze that varies between flight passes', 'why_missed': 'sky appears clear at ground level; smoke layer at altitude invisible from below; affects near-infrared more than visible', 'lesson': 'remote sensing is affected by atmospheric conditions not visible from the ground — smoke, dust, moisture at altitude', 'correct_response': 'Check regional air quality indices and atmospheric conditions at flight altitude, not just ground level visibility'},
        {'observable_symptoms': ['pollinator_decline', 'crops_not_setting_fruit', 'habitat_looks_fine'], 'obvious_suspects': ['pesticide_drift', 'disease', 'habitat_loss', 'climate_timing_mismatch'], 'actual_cause': 'LED lights on new adjacent greenhouse operating at night disrupting pollinator navigation and circadian rhythms', 'why_missed': 'artificial light at night (ALAN) effects on pollinators not widely known; greenhouse 500m away seems unrelated', 'lesson': 'artificial light at night disrupts insect behavior far beyond the immediate light source', 'correct_response': 'Survey nighttime light environment — any new light sources disrupting pollinator behavior? LED spectrum particularly affects insects'},
        {'observable_symptoms': ['precision_planter_seed_spacing_irregular', 'calibration_correct', 'new_seed_lot'], 'obvious_suspects': ['seed_size_variation', 'meter_disk_worn', 'vacuum_pressure_wrong', 'speed_too_fast'], 'actual_cause': 'seed treatment coating from new supplier has different electrostatic properties causing seeds to clump in meter', 'why_missed': 'seeds pass size grading; electrostatic properties not in seed spec; coating looks identical visually', 'lesson': 'surface properties (static charge, friction, coating) matter as much as dimensions for precision equipment', 'correct_response': 'Check if seed coating supplier or formulation changed — electrostatic and friction properties affect metering accuracy'},
    ],
    'defense': [
        {'observable_symptoms': ['communications_intermittent', 'specific_area', 'time_pattern'], 'obvious_suspects': ['enemy_jamming', 'equipment_failure', 'atmospheric_conditions', 'range_limitation'], 'actual_cause': 'allied exercise nearby using same frequency band — coordination failure between commands', 'why_missed': 'exercise schedule not shared across commands; interference looks like jamming; no hostile intent means no SIGINT alert', 'lesson': 'blue-on-blue interference is more common than enemy jamming — check deconfliction first', 'correct_response': 'Check allied exercise schedules and frequency deconfliction before assuming hostile jamming'},
        {'observable_symptoms': ['radar_ghost_returns', 'specific_bearing', 'consistent_timing'], 'obvious_suspects': ['electronic_warfare', 'atmospheric_ducting', 'equipment_malfunction', 'spoofing'], 'actual_cause': 'new civilian wind farm turbine blades creating radar returns that look like slow-moving aircraft', 'why_missed': 'wind farm permitting didnt include military notification; radar filters not updated for new obstruction', 'lesson': 'civilian infrastructure changes affect military systems — maintain awareness of nearby construction', 'correct_response': 'Check for new construction, wind farms, or tall structures along ghost return bearing'},
        {'observable_symptoms': ['GPS_degraded', 'specific_vehicles_only', 'intermittent'], 'obvious_suspects': ['GPS_spoofing', 'jamming', 'receiver_failure', 'solar_storm'], 'actual_cause': 'aftermarket LED light bar on vehicles emits RF interference in GPS L1 band when switched on', 'why_missed': 'EMI testing done without aftermarket accessories; correlation with light bar not obvious', 'lesson': 'aftermarket equipment can interfere with sensitive systems — test with all field modifications installed', 'correct_response': 'Check what aftermarket equipment is on affected vs unaffected vehicles — LEDs, radios, chargers can emit GPS-band interference'},
        {'observable_symptoms': ['weather_data_feeding_wrong_coordinates', 'targeting_affected', 'recent_onset'], 'obvious_suspects': ['sensor_failure', 'data_corruption', 'cyberattack_on_weather_system', 'configuration_error'], 'actual_cause': 'weather satellite provider changed coordinate reference frame in routine update without military notification', 'why_missed': 'civilian weather service update process doesnt include military user notification; offset is small but operationally significant', 'lesson': 'upstream civilian data providers can change formats and references without notifying military consumers', 'correct_response': 'Verify coordinate reference frame matches between weather provider and targeting system — check for provider updates'},
        {'observable_symptoms': ['encrypted_comms_sync_failures', 'dawn_and_dusk', 'specific_bases'], 'obvious_suspects': ['crypto_key_failure', 'clock_drift', 'enemy_crypto_attack', 'software_bug'], 'actual_cause': 'thermal expansion of antenna dish at dawn/dusk causes micro-misalignment corrupting bit stream', 'why_missed': 'thermal effects sub-degree; crypto layer interprets corrupted bits as sync failure not physical layer issue', 'lesson': 'crypto sync failures can have physical layer causes — dont assume symptom layer is cause layer', 'correct_response': 'Check if antenna systems have thermal alignment shifts — physical layer corruption presents as application layer failure'},
        {'observable_symptoms': ['perimeter_sensor_false_alarms', 'specific_zone', 'increasing_frequency'], 'obvious_suspects': ['sensor_degradation', 'wildlife', 'environmental_interference', 'calibration_drift'], 'actual_cause': 'construction off-base blocked drainage path, raising water table and changing ground vibration patterns', 'why_missed': 'seismic sensors calibrated to original conditions; off-base drainage change not monitored', 'lesson': 'ground truth changes over time — sensors calibrated to original conditions need recalibration when environment changes', 'correct_response': 'Check for environmental changes: construction, drainage, water table shifts altering ground vibration characteristics'},
        {'observable_symptoms': ['night_vision_degraded', 'specific_sector', 'recent_onset'], 'obvious_suspects': ['equipment_degradation', 'atmospheric_conditions', 'enemy_IR_countermeasures', 'battery'], 'actual_cause': 'new LED streetlights in nearby village produce IR bleed that saturates sensor in that direction', 'why_missed': 'civilian infrastructure changes not tracked; LED IR emission invisible to human eye; old sodium lights had different spectrum', 'lesson': 'sensor performance is relative to background — civilian lighting changes affect detection capability', 'correct_response': 'Check background illumination environment for new light sources — civilian upgrades affect IR background'},
        {'observable_symptoms': ['UAV_autopilot_altitude_errors', 'specific_region', 'consistent_offset'], 'obvious_suspects': ['barometric_sensor', 'GPS_altitude_error', 'terrain_database_outdated', 'calibration'], 'actual_cause': 'local magnetic anomaly from iron ore deposit biasing magnetometer-aided navigation', 'why_missed': 'geological surveys not integrated into nav system; anomaly maps not loaded; consistent error doesnt trigger fault detection', 'lesson': 'navigation fusing multiple sensors can be biased by local environmental conditions not in their models', 'correct_response': 'Check geological surveys for magnetic anomalies; verify magnetometer calibration accounts for regional variations'},
        {'observable_symptoms': ['supply_chain_delays', 'multiple_suppliers_affected', 'specific_components'], 'obvious_suspects': ['sanctions', 'manufacturing_recall', 'demand_surge', 'logistics_disruption'], 'actual_cause': 'single rare earth element supplier in China reduced export quotas — all manufacturers share upstream dependency', 'why_missed': 'tier 1 supply diversity hides tier N single-source dependencies; raw material source invisible', 'lesson': 'supply diversity at tier 1 doesnt guarantee diversity at tier N — trace critical materials to source', 'correct_response': 'Trace supply chain deeper — what raw materials do all affected suppliers share? Check for single-source dependencies at tier 2+'},
    ],
    'construction': [
        {'observable_symptoms': ['foundation_settling_unevenly', 'soil_report_was_clear', 'one_corner_sinking'], 'obvious_suspects': ['poor_compaction', 'soil_bearing_failure', 'drainage_issue', 'design_error'], 'actual_cause': 'underground stream not on any survey map — seasonal flow washes out soil beneath one corner', 'why_missed': 'geological survey done in dry season; stream only active in wet months; no historical knowledge of watercourse', 'lesson': 'single-season site surveys miss seasonal phenomena — always research full hydrological history', 'correct_response': 'Conduct wet-season hydrology assessment; research historical watercourse maps; probe for subsurface water flow paths'},
        {'observable_symptoms': ['cracks_appearing_in_new_building', 'no_structural_defects', 'progressive'], 'obvious_suspects': ['thermal_movement', 'structural_settlement', 'poor_materials', 'design_inadequacy'], 'actual_cause': 'neighbor demolition project causing ground vibration that propagates through shared geological stratum', 'why_missed': 'vibration below human perception; neighboring site not monitored; cracks attributed to normal settlement', 'lesson': 'nearby construction activity transmits vibration through ground affecting adjacent structures', 'correct_response': 'Install vibration monitors; check all nearby construction, demolition, or piling activity; correlate crack progression with neighbors schedule'},
        {'observable_symptoms': ['concrete_not_achieving_spec_strength', 'mix_design_verified', 'same_supplier'], 'obvious_suspects': ['water_cement_ratio_wrong', 'aggregate_quality', 'curing_conditions', 'testing_error'], 'actual_cause': 'admixture supplier changed source of fly ash — new ash has higher carbon content inhibiting hydration', 'why_missed': 'fly ash meets standard specifications; carbon content within spec limits but at high end; cumulative effect with other admixtures not tested', 'lesson': 'within-spec ingredients can still interact badly — test actual combinations, not just individual components', 'correct_response': 'Get full admixture supply chain traceability; test current actual mix combinations in lab, not just verify individual spec compliance'},
        {'observable_symptoms': ['steel_frame_alignment_drifting', 'survey_was_correct', 'hot_weather'], 'obvious_suspects': ['survey_error', 'fabrication_tolerances', 'erection_sequence_wrong', 'foundation_movement'], 'actual_cause': 'thermal expansion from direct sun on south face during erection — steel expanding 12mm over 30m span', 'why_missed': 'erection planned for spring but delayed to summer; thermal expansion calculation assumed average temp not peak solar gain', 'lesson': 'steel thermal expansion in direct sun far exceeds air temperature calculations — plan erection timing carefully', 'correct_response': 'Calculate actual steel temperature under solar radiation, not just air temp; consider erecting sun-exposed frames early morning'},
        {'observable_symptoms': ['waterproofing_failures', 'membrane_intact', 'leaks_at_penetrations'], 'obvious_suspects': ['poor_workmanship_at_details', 'membrane_damage', 'incompatible_sealant', 'substrate_movement'], 'actual_cause': 'fire stopping foam installer came after waterproofer and punctured membrane to install firestops at every penetration', 'why_missed': 'separate subcontractors; sequencing error in construction schedule; each trade inspected their own work as correct', 'lesson': 'multi-trade interfaces are where failures occur — one trades work can destroy anothers without either knowing', 'correct_response': 'Audit trade sequencing at all penetrations; check if later trades damaged earlier waterproofing; coordinate multi-trade inspections'},
        {'observable_symptoms': ['road_surface_deteriorating_prematurely', 'specific_section', 'design_life_not_reached'], 'obvious_suspects': ['subgrade_failure', 'traffic_overloading', 'material_defect', 'drainage_inadequate'], 'actual_cause': 'underlying utility trench backfilled with wrong material 2 years ago — differential settlement creating stress in pavement above', 'why_missed': 'utility work done by different agency; backfill compaction not verified by road authority; trench location not in road maintenance database', 'lesson': 'utility trenches in roads are future failure points if backfill isnt properly specified and verified', 'correct_response': 'Cross-reference deterioration location with all utility records; probe for differential settlement over buried trenches'},
        {'observable_symptoms': ['building_sway_complaints', 'structural_analysis_says_fine', 'specific_wind_direction'], 'obvious_suspects': ['vortex_shedding', 'design_underestimate', 'damper_failure', 'resonance'], 'actual_cause': 'adjacent new tower creates wind channeling effect (Venturi) not present when building was designed', 'why_missed': 'original wind study done without adjacent building; computational fluid dynamics not re-run after neighbor built', 'lesson': 'wind environment changes when surrounding buildings change — aerodynamic interactions create new loading patterns', 'correct_response': 'Commission updated wind study including all current surrounding buildings; check for channeling and vortex interaction effects'},
        {'observable_symptoms': ['elevator_shaft_pressure_issues', 'doors_hard_to_open', 'specific_floors'], 'obvious_suspects': ['stack_effect', 'HVAC_imbalance', 'shaft_seal_failure', 'lobby_pressure'], 'actual_cause': 'parking garage ventilation fans creating negative pressure at ground floor that propagates up elevator shaft', 'why_missed': 'garage ventilation and elevator systems designed by different engineers; system interaction not modeled', 'lesson': 'tall building air pressure is a connected system — changes in one zone propagate through shafts and stairs', 'correct_response': 'Map pressure differentials floor by floor; check for pressure sources/sinks in connected spaces — garages, mechanical rooms, lobbies'},
        {'observable_symptoms': ['noise_complaints_from_residents', 'no_obvious_source', 'low_frequency_hum'], 'obvious_suspects': ['HVAC_equipment', 'transformer_hum', 'plumbing_resonance', 'structural_vibration'], 'actual_cause': 'swimming pool wave machine in basement creating standing wave resonance in buildings structural frame', 'why_missed': 'pool equipment runs intermittently; frequency matches structural natural frequency by coincidence; felt on upper floors far from source', 'lesson': 'any periodic excitation near a structures natural frequency will amplify — check all rotating or oscillating equipment', 'correct_response': 'Measure vibration frequency and compare to buildings natural frequencies; inventory all periodic equipment including recreational'},
    ],
    'space': [
        {'observable_symptoms': ['computer_reset_unexpectedly', 'single_event', 'no_software_cause_found'], 'obvious_suspects': ['software_bug', 'power_supply_glitch', 'thermal_shutdown', 'watchdog_timeout'], 'actual_cause': 'cosmic ray single-event upset (SEU) flipped a bit in memory causing invalid instruction execution', 'why_missed': 'single event, non-reproducible; ground testing cant replicate space radiation environment; error correcting memory covered most but not all', 'lesson': 'in space, random bit-flips from cosmic rays are a constant threat — design for them, dont debug them', 'correct_response': 'Check if event correlates with solar activity or SAA passage; verify ECC coverage; classify as SEU rather than debugging software'},
        {'observable_symptoms': ['star_tracker_giving_wrong_attitude', 'gradual_offset', 'thermal_cycle_correlated'], 'obvious_suspects': ['optics_contamination', 'algorithm_error', 'catalog_mismatch', 'CCD_degradation'], 'actual_cause': 'thermal expansion of mounting bracket shifts star tracker alignment relative to spacecraft body by 0.01 degrees per cycle', 'why_missed': 'bracket tested at single temperature; actual orbital thermal cycling creates creep in mounting; calibration done at one thermal state', 'lesson': 'thermal expansion causes sensor misalignment that accumulates — bracket materials and thermal environment must be precisely modeled', 'correct_response': 'Correlate attitude error with thermal state; recalibrate star tracker alignment at multiple orbital thermal conditions'},
        {'observable_symptoms': ['solar_panel_output_lower_than_model', 'degradation_faster_than_predicted', 'specific_orbit'], 'obvious_suspects': ['radiation_damage', 'contamination', 'pointing_error', 'cell_failure'], 'actual_cause': 'thruster plume contamination depositing thin film on panel surface during specific maneuver orientations', 'why_missed': 'plume model didnt account for backflow at specific angles; contamination is molecular-thin and invisible; builds up over many maneuvers', 'lesson': 'propulsion system contamination is cumulative and geometry-dependent — monitor after every maneuver, not just annually', 'correct_response': 'Correlate power degradation timeline with maneuver history; check if specific thrust vectors point plume toward panels'},
        {'observable_symptoms': ['communication_link_margin_declining', 'no_antenna_issue', 'gradual'], 'obvious_suspects': ['amplifier_degradation', 'antenna_pointing_error', 'atmospheric_attenuation', 'interference'], 'actual_cause': 'ground station suburban expansion — new housing development increased RF noise floor at receiving station', 'why_missed': 'link budget calculated at station commissioning; local RF environment worsens over years; noise floor not re-baselined', 'lesson': 'ground station RF environment degrades over time as civilization expands nearby — periodic re-assessment needed', 'correct_response': 'Re-measure ground station noise floor; compare to original commissioning baseline; survey local development for new RF sources'},
        {'observable_symptoms': ['reaction_wheel_vibration_increasing', 'bearing_analysis_inconclusive', 'specific_speed_range'], 'obvious_suspects': ['bearing_wear', 'imbalance', 'cage_instability', 'lubricant_degradation'], 'actual_cause': 'structural resonance between wheel speed and solar panel natural frequency — coupling through spacecraft bus at specific RPM', 'why_missed': 'wheel and panels analyzed separately; coupled structural model not updated after panel deployment; resonance only at specific RPM range', 'lesson': 'spacecraft is a coupled dynamic system — component analyses miss system-level resonances', 'correct_response': 'Run coupled structural analysis at all wheel operating speeds; check for resonance between wheel harmonics and deployed appendage modes'},
        {'observable_symptoms': ['payload_data_quality_degraded', 'specific_orbit_segments', 'periodic'], 'obvious_suspects': ['instrument_issue', 'thermal_effects', 'radiation_belt_interference', 'data_handling_error'], 'actual_cause': 'heater on adjacent component cycling on/off creates EMI that couples into instrument data lines during eclipse thermal control', 'why_missed': 'heater EMI tested in isolation but not while instrument acquiring data; eclipse thermal cycling activates heaters at specific cadence', 'lesson': 'spacecraft EMC is state-dependent — test electromagnetic compatibility in all operational thermal and power modes, not just nominal', 'correct_response': 'Correlate data quality with heater duty cycles; check EMI coupling between thermal control and instrument data paths during eclipse'},
        {'observable_symptoms': ['orbit_determination_residuals_growing', 'tracking_data_looks_fine', 'force_model_unchanged'], 'obvious_suspects': ['unmodeled_maneuver', 'atmospheric_drag_error', 'solar_pressure_miscalculation', 'station_bias'], 'actual_cause': 'small propellant leak creating micro-thrust that is below detection threshold but accumulates in orbit determination', 'why_missed': 'leak too small for pressure sensors to detect; thrust equivalent is nano-Newton range; only visible in precision orbit determination residuals', 'lesson': 'unexplained orbit determination residuals often reveal real physical forces — dont just tune the filter, find the source', 'correct_response': 'Analyze residual pattern for directionality consistent with a fixed-body-frame force; check propulsion telemetry for subtle pressure trends'},
        {'observable_symptoms': ['mechanism_stalled', 'motor_current_normal', 'temperature_nominal'], 'obvious_suspects': ['mechanism_jam', 'gear_failure', 'launch_damage', 'debris_impact'], 'actual_cause': 'cold welding between metal surfaces in vacuum — surfaces that separated fine in ground testing fused in space vacuum', 'why_missed': 'ground testing includes atmosphere that prevents cold welding; mechanism worked during ground test; vacuum exposure time creates weld', 'lesson': 'vacuum conditions enable failure modes impossible to reproduce in ground testing — cold welding, outgassing seizure', 'correct_response': 'Consider vacuum-specific failure modes: cold welding, outgassing products creating adhesive films, lubricant evaporation'},
        {'observable_symptoms': ['imaging_instrument_shows_artifacts', 'specific_detector_region', 'time_dependent'], 'obvious_suspects': ['detector_degradation', 'contamination', 'electronics_noise', 'radiation_damage'], 'actual_cause': 'outgassing from nearby adhesive depositing on cold detector surface — contamination layer grows over mission life', 'why_missed': 'material screening passed standard tests; outgassing rate very low but accumulates on coldest surface over years; periodic bakeout helps but doesnt fully resolve', 'lesson': 'molecular contamination migrates to coldest surfaces over time — long-duration missions need contamination budgets and bakeout plans', 'correct_response': 'Schedule detector bakeout if possible; trace contamination source through molecular transport modeling; check outgassing rates of all materials in instrument cavity'},
    ],
    'insurance': [
        {'observable_symptoms': ['claims_spike_specific_region', 'no_weather_event', 'no_news'], 'obvious_suspects': ['fraud_ring', 'reporting_lag', 'seasonal_pattern', 'policy_change_effect'], 'actual_cause': 'local contractor going door-to-door convincing homeowners they have storm damage from months-old event — generating legitimate but unnecessary claims', 'why_missed': 'each individual claim is legitimate; pattern only visible in aggregate; contractor activity not monitored', 'lesson': 'claims clusters without obvious cause often have a human catalyst — contractors, lawyers, or social media driving behavior', 'correct_response': 'Check for common contractors, adjusters, or attorneys across clustered claims; investigate solicitation activity in the area'},
        {'observable_symptoms': ['auto_claims_severity_increasing', 'frequency_stable', 'same_vehicle_mix'], 'obvious_suspects': ['repair_cost_inflation', 'parts_availability', 'new_vehicle_technology_costs', 'fraud'], 'actual_cause': 'ADAS calibration requirements after windshield replacement — $500 recalibration added to every glass claim on modern vehicles', 'why_missed': 'windshield claims historically low-severity; ADAS calibration requirement new and not in legacy cost models; coded as glass but includes electronics', 'lesson': 'vehicle technology changes create hidden cost drivers in historically simple claim categories', 'correct_response': 'Audit cost components in increasing-severity categories; check for new repair requirements from ADAS, EV batteries, or embedded technology'},
        {'observable_symptoms': ['life_insurance_lapses_increasing', 'same_demographics', 'economy_stable'], 'obvious_suspects': ['competitive_pressure', 'pricing_issue', 'customer_service_problem', 'product_mismatch'], 'actual_cause': 'financial wellness app recommending users cancel whole life policies as bad investment — algorithmic financial advice driving behavior', 'why_missed': 'fintech app recommendations invisible to insurer; customers dont state reason as app advice; each decision looks individual', 'lesson': 'automated financial advice platforms can drive correlated policyholder behavior invisible to insurers', 'correct_response': 'Survey lapsing customers about information sources; monitor fintech and social media for narratives about your product category'},
        {'observable_symptoms': ['workers_comp_claims_new_diagnosis_pattern', 'specific_industry', 'gradual_increase'], 'obvious_suspects': ['new_occupational_hazard', 'awareness_campaign', 'legal_precedent_change', 'diagnostic_criteria_change'], 'actual_cause': 'single occupational medicine clinic marketing MRI screenings to employers — finding pre-existing conditions and attributing them to work', 'why_missed': 'each individual claim has legitimate diagnosis; over-utilization pattern only visible across many claims; clinic is licensed and findings are real', 'lesson': 'supply-driven demand in healthcare creates claims — a new clinic or test availability generates findings that become claims', 'correct_response': 'Analyze provider concentration in claims growth; check if specific clinics or testing facilities are disproportionately represented'},
        {'observable_symptoms': ['cyber_insurance_loss_ratios_deteriorating', 'diverse_insureds', 'no_common_vendor'], 'obvious_suspects': ['systemic_vulnerability', 'threat_actor_campaign', 'underpricing', 'coverage_expansion'], 'actual_cause': 'single widely-used open source library had vulnerability — all insureds use it but its buried in dependency trees and not identified as common', 'why_missed': 'software bill of materials not collected at underwriting; common dependency invisible in application-level assessments', 'lesson': 'cyber risk aggregation hides in shared open source dependencies invisible to traditional underwriting', 'correct_response': 'Analyze compromised systems for common software components including transitive dependencies; SBOM analysis reveals hidden aggregation risk'},
        {'observable_symptoms': ['property_claims_from_slow_leak_water_damage', 'newer_homes', 'specific_builder'], 'obvious_suspects': ['plumbing_defect', 'installation_error', 'material_failure', 'soil_movement'], 'actual_cause': 'builder used specific brand of PEX fittings that fail after 5-7 years due to dezincification — ticking time bomb across all their homes', 'why_missed': 'fittings approved and warranted at installation; failure mode is time-dependent; individual claims dont reveal common component', 'lesson': 'construction defect claims with time-delayed onset require analysis by builder, component, and installation date cohort', 'correct_response': 'Cohort analysis by builder, installation year, and component brand; check industry bulletins for time-dependent material failures'},
        {'observable_symptoms': ['commercial_auto_losses_up', 'telematics_shows_safe_driving', 'same_routes'], 'obvious_suspects': ['telematics_gaming', 'road_conditions_worsened', 'vehicle_maintenance', 'third_party_fraud'], 'actual_cause': 'new distribution center brought heavy truck traffic to previously quiet roads — other vehicles are causing the accidents, not the insured fleet', 'why_missed': 'telematics monitors insured vehicles not the risk environment around them; road risk assessment static from policy inception', 'lesson': 'vehicle risk depends on the surrounding traffic environment, not just driver behavior — road risk profiles change', 'correct_response': 'Analyze not just insured driver behavior but the corridors they travel — has traffic mix, volume, or road condition changed on their routes?'},
        {'observable_symptoms': ['earthquake_model_under_predicting_losses', 'moderate_event', 'well_modeled_region'], 'obvious_suspects': ['model_ground_motion_wrong', 'vulnerability_functions_outdated', 'exposure_data_stale', 'demand_surge'], 'actual_cause': 'pre-event retrofit incentive program led owners to report structures as retrofitted without actually completing work — model assumes upgraded building stock', 'why_missed': 'permit data shows retrofits; physical completion not verified; model ingests permit data as completed work', 'lesson': 'model inputs based on permits or self-reporting may not reflect physical reality — verify a sample', 'correct_response': 'Cross-validate model exposure assumptions against post-event damage patterns; sample physical verification of reported retrofits'},
        {'observable_symptoms': ['health_insurance_ER_visits_spiking', 'non_emergency_diagnoses', 'specific_zip_codes'], 'obvious_suspects': ['lack_of_primary_care_access', 'patient_education', 'urgent_care_closures', 'after_hours_need'], 'actual_cause': 'ride-share company partnered with hospital for free ER rides — patients using ER for primary care because transportation is provided', 'why_missed': 'transportation barrier removal is positive in isolation; unintended consequence of steering to ER not PCP; partnership not known to insurer', 'lesson': 'access interventions can redirect utilization in unintended ways — removing one barrier may route to expensive care', 'correct_response': 'Investigate transportation and access programs in affected zip codes; check if non-clinical factors are routing patients to ER vs appropriate care settings'},
    ],
}


class UnknownUnknownsEngine:
    """Engine that injects unknown-unknowns scenarios into training records.

    Teaches AI to recognize when:
    - The correct answer is NONE of the obvious choices
    - The real cause is something nobody considered
    - More data is needed before concluding
    """

    def __init__(self, rng: random.Random):
        self.rng = rng

    def inject(self, record: Dict, world: str) -> Dict:
        """8% of records get unknown-unknowns layer."""
        if self.rng.random() < 0.08:
            scenarios = WORLD_UNKNOWNS.get(world, WORLD_UNKNOWNS.get('coding', []))
            if scenarios:
                uu = self.rng.choice(scenarios)
                ai = record.get('_ai_training', {})
                ai['unknown_unknown'] = uu
                record['_ai_training'] = ai
        return record
