"""AXIMA Capability Ledger — machine-readable feature status tracking.

Each feature has four lifecycle states:
- IMPLEMENTED: Code exists in the codebase
- WIRED: Code is connected to the router/API
- VERIFIED: Automated tests pass for this feature
- VALIDATED: Eval benchmarks confirm real-world performance

The ledger is generated by introspecting the actual filesystem and eval results.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path
from typing import Sequence


class FeatureState(Enum):
    """Lifecycle state of a feature."""

    IMPLEMENTED = "IMPLEMENTED"  # Code exists
    WIRED = "WIRED"              # Connected to router
    VERIFIED = "VERIFIED"        # Tests pass
    VALIDATED = "VALIDATED"      # Evals confirm performance


@dataclass(frozen=True)
class FeatureStatus:
    """Status of a single feature across all lifecycle states."""

    name: str
    category: str
    implemented: bool = False
    wired: bool = False
    verified: bool = False
    validated: bool = False

    @property
    def state(self) -> FeatureState:
        """Return the highest achieved lifecycle state."""
        if self.validated:
            return FeatureState.VALIDATED
        if self.verified:
            return FeatureState.VERIFIED
        if self.wired:
            return FeatureState.WIRED
        if self.implemented:
            return FeatureState.IMPLEMENTED
        return FeatureState.IMPLEMENTED  # minimum — code must exist to be in ledger

    def to_dict(self) -> dict[str, object]:
        """Serialize to dict for JSON output."""
        return {
            "name": self.name,
            "category": self.category,
            "state": self.state.value,
            "implemented": self.implemented,
            "wired": self.wired,
            "verified": self.verified,
            "validated": self.validated,
        }


@dataclass
class CapabilityLedger:
    """Complete capability ledger for the AXIMA system."""

    features: list[FeatureStatus] = field(default_factory=list)

    def add(self, feature: FeatureStatus) -> None:
        """Add a feature to the ledger."""
        self.features.append(feature)

    def to_json(self, indent: int = 2) -> str:
        """Serialize ledger to JSON."""
        data = {
            "version": "0.1.0",
            "total_features": len(self.features),
            "summary": self._summary(),
            "features": [f.to_dict() for f in self.features],
        }
        return json.dumps(data, indent=indent)

    def _summary(self) -> dict[str, int]:
        """Count features by highest achieved state."""
        counts = {s.value: 0 for s in FeatureState}
        for f in self.features:
            counts[f.state.value] += 1
        return counts

    @property
    def categories(self) -> list[str]:
        """Return sorted list of unique categories."""
        return sorted(set(f.category for f in self.features))


def _check_file_exists(base: Path, *candidates: str) -> bool:
    """Check if any of the candidate paths exist."""
    for c in candidates:
        if (base / c).exists():
            return True
    return False


def _check_eval_exists(evals_dir: Path, category: str) -> bool:
    """Check if eval cases exist for a category."""
    cases_file = evals_dir / category / "cases.json"
    return cases_file.is_file()


def generate_ledger() -> CapabilityLedger:
    """Generate the capability ledger by introspecting the codebase."""
    from axima.config import SRC_PYTHON_DIR, EVALS_DIR, AXIMA_HOME

    ledger = CapabilityLedger()

    # Define all known features with their detection criteria
    feature_defs: list[dict[str, object]] = [
        {
            "name": "Symbolic Math Solver",
            "category": "math",
            "files": ["prometheus.py", "prometheus_advanced.py"],
            "router_key": "math",
            "eval_category": "math",
        },
        {
            "name": "Physics Solver",
            "category": "physics",
            "files": ["prometheus_physics.py", "prometheus_physics_solve.py"],
            "router_key": "physics",
            "eval_category": None,
        },
        {
            "name": "Inference Engine",
            "category": "knowledge",
            "files": ["inference_engine.py"],
            "router_key": "inference",
            "eval_category": None,
        },
        {
            "name": "Code Router",
            "category": "coder",
            "files": ["coder.py"],
            "router_key": "code",
            "eval_category": "codegen",
        },
        {
            "name": "Algorithm Generator",
            "category": "coder",
            "files": ["codegen_engine.py"],
            "router_key": "code",
            "eval_category": "codegen",
        },
        {
            "name": "Project Generator",
            "category": "coder",
            "files": ["axima_coder.py", "cosmic_coder.py"],
            "router_key": "code",
            "eval_category": None,
        },
        {
            "name": "Web Generator",
            "category": "web",
            "files": ["web_generator.py", "web_beyond.py"],
            "router_key": "web",
            "eval_category": "web",
        },
        {
            "name": "Multilingual Detection",
            "category": "multilingual",
            "files": ["multilingual/"],
            "router_key": "multilingual",
            "eval_category": "multilingual",
        },
        {
            "name": "Content Creator",
            "category": "creator",
            "files": ["creator/"],
            "router_key": "creator",
            "eval_category": None,
        },
        {
            "name": "ACES Explanation Pipeline",
            "category": "explanation",
            "files": ["aces_v2/"],
            "router_key": "explain",
            "eval_category": "explanation",
        },
        {
            "name": "Brain Document Q&A",
            "category": "brain",
            "files": ["brain_ingest.py", "brain_study.py", "brain_reason.py"],
            "router_key": "brain",
            "eval_category": None,
        },
        {
            "name": "Knowledge Index",
            "category": "knowledge",
            "files": ["knowledge_index.py"],
            "router_key": "knowledge",
            "eval_category": None,
        },
        {
            "name": "Truth Labels",
            "category": "core",
            "files": ["truth.py"],
            "router_key": "truth",
            "eval_category": None,
        },
        {
            "name": "Error Architecture",
            "category": "core",
            "files": ["errors.py"],
            "router_key": "errors",
            "eval_category": None,
        },
        {
            "name": "Execution Tracer",
            "category": "core",
            "files": ["tracer.py"],
            "router_key": "tracer",
            "eval_category": None,
        },
    ]

    # Check router wiring by inspecting axima.py
    router_file = SRC_PYTHON_DIR / "axima.py"
    router_source = ""
    if router_file.is_file():
        try:
            router_source = router_file.read_text(encoding="utf-8")
        except OSError:
            pass

    tests_dir = AXIMA_HOME / "tests"

    for fdef in feature_defs:
        name = str(fdef["name"])
        category = str(fdef["category"])
        files = fdef["files"]
        assert isinstance(files, list)
        router_key = str(fdef["router_key"])
        eval_category = fdef.get("eval_category")

        # IMPLEMENTED: source files exist
        implemented = _check_file_exists(SRC_PYTHON_DIR, *[str(f) for f in files])

        # WIRED: router references this engine
        wired = implemented and (router_key in router_source.lower())

        # VERIFIED: test files exist for this feature
        verified = False
        if tests_dir.is_dir():
            for test_file in tests_dir.rglob("*.py"):
                try:
                    content = test_file.read_text(encoding="utf-8")
                    if category in content.lower() or name.lower().split()[0] in content.lower():
                        verified = True
                        break
                except OSError:
                    pass

        # VALIDATED: eval cases exist and have been run
        validated = False
        if eval_category and isinstance(eval_category, str):
            validated = _check_eval_exists(EVALS_DIR, eval_category)

        ledger.add(FeatureStatus(
            name=name,
            category=category,
            implemented=implemented,
            wired=wired,
            verified=verified,
            validated=validated,
        ))

    return ledger


def get_ledger_json(indent: int = 2) -> str:
    """Generate and return the ledger as JSON string."""
    ledger = generate_ledger()
    return ledger.to_json(indent=indent)


def print_ledger() -> None:
    """Print the capability ledger in human-readable format."""
    ledger = generate_ledger()

    print("AXIMA Capability Ledger")
    print("=" * 70)
    print(f"{'Feature':<30} {'Category':<14} {'State':<12} I  W  V  D")
    print("-" * 70)

    for f in ledger.features:
        i = "✓" if f.implemented else "·"
        w = "✓" if f.wired else "·"
        v = "✓" if f.verified else "·"
        d = "✓" if f.validated else "·"
        print(f"  {f.name:<28} {f.category:<14} {f.state.value:<12} {i}  {w}  {v}  {d}")

    print("-" * 70)
    summary = ledger._summary()
    print(f"  Total: {len(ledger.features)} features")
    for state, count in summary.items():
        if count > 0:
            print(f"    {state}: {count}")
    print()


if __name__ == "__main__":
    print_ledger()
